# flake8: noqa

def b3_to_csv() -> str: ...
def load_from_b3(b3_string: str) -> int: ...
def remove_ob_key(key: int) -> None: ...
def get_ob_field(key: int, field: str) -> str: ...
def get_ob_array(key: int) -> list[float]: ...
