import os
from typing import Any

__version__: str

class Context:
    def eval(self, source: str) -> Any: ...
    def eval_from_bytes(self, source: str) -> Any: ...
    def eval_from_filepath(self, source: str | os.PathLike[str]) -> Any: ...

class Undefined: ...
class PanicException(BaseException): ...
