"""
    Emil PublicAPI

    The Emil Public API description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@emil.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eis.publicapi
from eis.publicapi.model.product_field_class import ProductFieldClass
globals()['ProductFieldClass'] = ProductFieldClass
from eis.publicapi.model.insured_object_class import InsuredObjectClass


class TestInsuredObjectClass(unittest.TestCase):
    """InsuredObjectClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInsuredObjectClass(self):
        """Test InsuredObjectClass"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InsuredObjectClass()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
