"""
    Emil PublicAPI

    The Emil Public API description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@emil.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eis.publicapi
from eis.publicapi.model.structured_address_class import StructuredAddressClass


class TestStructuredAddressClass(unittest.TestCase):
    """StructuredAddressClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStructuredAddressClass(self):
        """Test StructuredAddressClass"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StructuredAddressClass()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
