# Generated by Django 4.2.7 on 2024-10-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparkplug_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created',)},
        ),
    ]
