
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-10-23T15:43:23-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ce59274617ace41533270fb481325f6d223ac6d",
 "version": "2.73.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
