import tensorflow as tf

SWITCH_ON: bool

def is_tensor(x) -> bool: ...
def has_tensor(x) -> bool: ...
def allclose_anyaware(x, y, rtol: float = 1e-05, atol: float = 1e-08) -> bool: ...
def broadcast_to(input, shape) -> tf.Tensor: ...
def expand_dims(input, axis) -> tf.Tensor: ...
def reduce_prod(input_tensor, axis=None, keepdims=None) -> tf.Tensor: ...
def equal(x, y) -> tf.Tensor: ...
def reduce_all(input_tensor, axis=None) -> tf.Tensor: ...
def reduce_any(input_tensor, axis=None) -> tf.Tensor: ...
def logical_and(x, y) -> tf.Tensor: ...
def logical_or(x, y) -> tf.Tensor: ...
def less_equal(x, y) -> tf.Tensor: ...
def greater_equal(x, y) -> tf.Tensor: ...
def gather(x, indices=None, axis=None) -> tf.Tensor: ...
def concat(values, axis) -> tf.Tensor: ...
