# src/pico_ioc/__init__.py
from .constants import LOGGER_NAME, LOGGER, PICO_INFRA, PICO_NAME, PICO_KEY, PICO_META
from .exceptions import (
    PicoError,
    ProviderNotFoundError,
    CircularDependencyError,
    ComponentCreationError,
    ScopeError,
    ConfigurationError,
    SerializationError,
    ValidationError,
    InvalidBindingError,
    EventBusClosedError,
)
from .api import (
    component,
    factory,
    provides,
    Qualifier,
    qualifier,
    on_missing,
    primary,
    conditional,
    lazy,
    configuration,
    configure,
    cleanup,
    scope,
    ConfigSource,
    EnvSource,
    FileSource,
    init,
    configured,
)
from .scope import ScopeManager, ContextVarScope, ScopeProtocol, ScopedCaches
from .locator import ComponentLocator
from .factory import ComponentFactory, ProviderMetadata, DeferredProvider
from .aop import MethodCtx, MethodInterceptor, intercepted_by, UnifiedComponentProxy, health, ContainerObserver
from .container import PicoContainer
from .event_bus import EventBus, ExecPolicy, ErrorPolicy, Event, subscribe, AutoSubscriberMixin
from .config_runtime import JsonTreeSource, YamlTreeSource, DictSource, Discriminator

__all__ = [
    "LOGGER_NAME",
    "LOGGER",
    "PICO_INFRA",
    "PICO_NAME",
    "PICO_KEY",
    "PICO_META",
    "PicoError",
    "ProviderNotFoundError",
    "CircularDependencyError",
    "ComponentCreationError",
    "ScopeError",
    "ConfigurationError",
    "SerializationError",
    "ValidationError",
    "InvalidBindingError",
    "EventBusClosedError",
    "component",
    "factory",
    "provides",
    "Qualifier",
    "qualifier",
    "on_missing",
    "primary",
    "conditional",
    "lazy",
    "configuration",
    "configure",
    "cleanup",
    "scope",
    "ScopeProtocol",
    "ContextVarScope",
    "ScopeManager",
    "ComponentLocator",
    "ScopedCaches",
    "ProviderMetadata",
    "ComponentFactory",
    "DeferredProvider",
    "MethodCtx",
    "MethodInterceptor",
    "intercepted_by",
    "UnifiedComponentProxy",
    "health",
    "ContainerObserver",
    "PicoContainer",
    "EnvSource",
    "FileSource",
    "ConfigSource",
    "init",
    "configured",
    "EventBus",
    "ExecPolicy",
    "ErrorPolicy",
    "Event",
    "subscribe",
    "AutoSubscriberMixin",
    "JsonTreeSource",
    "YamlTreeSource",
    "DictSource",
    "Discriminator",
]

