# coding: utf-8

"""
    Sonatype Lifecycle Public REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.196.0-01
    Contact: community@sonatype.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonatype_iq_api_client.models.applicable_labels import ApplicableLabels

class TestApplicableLabels(unittest.TestCase):
    """ApplicableLabels unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplicableLabels:
        """Test ApplicableLabels
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplicableLabels`
        """
        model = ApplicableLabels()
        if include_optional:
            return ApplicableLabels(
                labels_by_owner = [
                    sonatype_iq_api_client.models.labels_by_owner.LabelsByOwner(
                        labels = [
                            sonatype_iq_api_client.models.api_label_dto.ApiLabelDTO(
                                color = '', 
                                description = '', 
                                id = '', 
                                label = '', 
                                owner_id = '', 
                                owner_type = '', )
                            ], 
                        owner_id = '', 
                        owner_name = '', 
                        owner_type = 'application', )
                    ]
            )
        else:
            return ApplicableLabels(
        )
        """

    def testApplicableLabels(self):
        """Test ApplicableLabels"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
