# coding: utf-8

"""
    Sonatype Lifecycle Public REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.196.0-01
    Contact: community@sonatype.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonatype_iq_api_client.api.components_api import ComponentsApi


class TestComponentsApi(unittest.TestCase):
    """ComponentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ComponentsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_component_label(self) -> None:
        """Test case for delete_component_label

        """
        pass

    def test_get_component_details(self) -> None:
        """Test case for get_component_details

        """
        pass

    def test_get_component_versions(self) -> None:
        """Test case for get_component_versions

        """
        pass

    def test_get_suggested_remediation_for_component(self) -> None:
        """Test case for get_suggested_remediation_for_component

        """
        pass

    def test_set_component_label(self) -> None:
        """Test case for set_component_label

        """
        pass


if __name__ == '__main__':
    unittest.main()
