# coding: utf-8

"""
    Sonatype Lifecycle Public REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.196.0-01
    Contact: community@sonatype.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonatype_iq_api_client.api.config_proxy_server_api import ConfigProxyServerApi


class TestConfigProxyServerApi(unittest.TestCase):
    """ConfigProxyServerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConfigProxyServerApi()

    def tearDown(self) -> None:
        pass

    def test_delete_configuration3(self) -> None:
        """Test case for delete_configuration3

        """
        pass

    def test_get_configuration3(self) -> None:
        """Test case for get_configuration3

        """
        pass

    def test_set_configuration3(self) -> None:
        """Test case for set_configuration3

        """
        pass


if __name__ == '__main__':
    unittest.main()
