# coding: utf-8

"""
    Sonatype Lifecycle Public REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.196.0-01
    Contact: community@sonatype.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonatype_iq_api_client.api.endpoints_api import EndpointsApi


class TestEndpointsApi(unittest.TestCase):
    """EndpointsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EndpointsApi()

    def tearDown(self) -> None:
        pass

    def test_get_open_api(self) -> None:
        """Test case for get_open_api

        """
        pass


if __name__ == '__main__':
    unittest.main()
