# coding: utf-8

"""
    Sonatype Lifecycle Public REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.196.0-01
    Contact: community@sonatype.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonatype_iq_api_client.api.audit_logs_api import AuditLogsApi


class TestAuditLogsApi(unittest.TestCase):
    """AuditLogsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuditLogsApi()

    def tearDown(self) -> None:
        pass

    def test_get_audit_logs(self) -> None:
        """Test case for get_audit_logs

        """
        pass


if __name__ == '__main__':
    unittest.main()
