from typing import Any, List, Optional

from com.google.common.collect import Range
from dev.coatl.helper.types import AnyStr
from java.io import InputStream
from java.lang import Enum, Object

class HttpClient(Object):
    def __init__(self) -> None: ...
    def getLastRequest(self) -> Request: ...
    def getLastResponse(self) -> Response: ...
    def nmakeRequest(self, request: Request) -> Response: ...
    def reliableRequest(
        self,
        request: Request,
        retryCodes: Optional[List[int]] = ...,
        retries: Optional[int] = ...,
        delayMillis: Optional[long] = ...,
    ) -> Response: ...

class HttpMethod(Enum):
    DELETE: str
    GET: str
    HEAD: str
    OPTIONS: str
    POST: str
    PUT: str
    @staticmethod
    def forValue(value: AnyStr) -> HttpMethod: ...
    @staticmethod
    def values() -> List[HttpMethod]: ...

class Request(Object):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def addPostParam(self, name: AnyStr, value: AnyStr) -> None: ...
    def addQueryDateRange(self, name: AnyStr, range: Range) -> None: ...

class Response(Object):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def getContent(self) -> AnyStr: ...
    def getStatusCode(self) -> int: ...
    def getStream(self) -> InputStream: ...

class TwilioRestClient(Object):
    class Builder(Object):
        def __init__(self, username: AnyStr, password: AnyStr) -> None: ...
        def accountSid(self, accountSid: AnyStr) -> TwilioRestClient.Builder: ...
        def build(self) -> TwilioRestClient: ...
        def httpClient(self, httpClient: Object) -> TwilioRestClient.Builder: ...
        def region(self, region: AnyStr) -> TwilioRestClient.Builder: ...

    HTTP_STATUS_CODE_CREATED: int
    HTTP_STATUS_CODE_NO_CONTENT: int
    HTTP_STATUS_CODE_OK: int
    def getAccountSid(self) -> AnyStr: ...
    def getHttpClient(self) -> HttpClient: ...
    def getObjectMapper(self) -> Object: ...
    def getRegion(self) -> AnyStr: ...
    def request(self, request: Request) -> Response: ...
