# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum_one_log_level.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='enum_one_log_level.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\021ONE.Models.CSharp'),
  serialized_pb=_b('\n\x18\x65num_one_log_level.proto*\xc0\x01\n\x0f\x45numOneLogLevel\x12\x19\n\x15ONE_LOG_LEVEL_UNKNOWN\x10\x00\x12\x17\n\x13ONE_LOG_LEVEL_FATAL\x10\x01\x12\x17\n\x13ONE_LOG_LEVEL_ERROR\x10\x02\x12\x16\n\x12ONE_LOG_LEVEL_WARN\x10\x03\x12\x16\n\x12ONE_LOG_LEVEL_INFO\x10\x04\x12\x17\n\x13ONE_LOG_LEVEL_DEBUG\x10\x05\x12\x17\n\x13ONE_LOG_LEVEL_TRACE\x10\x06\x42\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')
)

_ENUMONELOGLEVEL = _descriptor.EnumDescriptor(
  name='EnumOneLogLevel',
  full_name='EnumOneLogLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ONE_LOG_LEVEL_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONE_LOG_LEVEL_FATAL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONE_LOG_LEVEL_ERROR', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONE_LOG_LEVEL_WARN', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONE_LOG_LEVEL_INFO', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONE_LOG_LEVEL_DEBUG', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONE_LOG_LEVEL_TRACE', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=29,
  serialized_end=221,
)
_sym_db.RegisterEnumDescriptor(_ENUMONELOGLEVEL)

EnumOneLogLevel = enum_type_wrapper.EnumTypeWrapper(_ENUMONELOGLEVEL)
ONE_LOG_LEVEL_UNKNOWN = 0
ONE_LOG_LEVEL_FATAL = 1
ONE_LOG_LEVEL_ERROR = 2
ONE_LOG_LEVEL_WARN = 3
ONE_LOG_LEVEL_INFO = 4
ONE_LOG_LEVEL_DEBUG = 5
ONE_LOG_LEVEL_TRACE = 6


DESCRIPTOR.enum_types_by_name['EnumOneLogLevel'] = _ENUMONELOGLEVEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
