# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum_aggregate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='enum_aggregate.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\021ONE.Models.CSharp'),
  serialized_pb=_b('\n\x14\x65num_aggregate.proto*k\n\rEnumAggregate\x12\x15\n\x11\x41GGREGATE_UNKNOWN\x10\x00\x12\x15\n\x11\x41GGREGATE_MINIMUM\x10\x01\x12\x15\n\x11\x41GGREGATE_MAXIMUM\x10\x02\x12\x15\n\x11\x41GGREGATE_AVERAGE\x10\x03\x42\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')
)

_ENUMAGGREGATE = _descriptor.EnumDescriptor(
  name='EnumAggregate',
  full_name='EnumAggregate',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AGGREGATE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AGGREGATE_MINIMUM', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AGGREGATE_MAXIMUM', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AGGREGATE_AVERAGE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=24,
  serialized_end=131,
)
_sym_db.RegisterEnumDescriptor(_ENUMAGGREGATE)

EnumAggregate = enum_type_wrapper.EnumTypeWrapper(_ENUMAGGREGATE)
AGGREGATE_UNKNOWN = 0
AGGREGATE_MINIMUM = 1
AGGREGATE_MAXIMUM = 2
AGGREGATE_AVERAGE = 3


DESCRIPTOR.enum_types_by_name['EnumAggregate'] = _ENUMAGGREGATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
