# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instrument_tag_definition.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import instrument_tag_identifier_pb2 as instrument__tag__identifier__pb2
from . import claros_i18nkey_text_reference_pb2 as claros__i18nkey__text__reference__pb2
from . import enum_instrument_data_attribute_priority_pb2 as enum__instrument__data__attribute__priority__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='instrument_tag_definition.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\034ONE.Models.CSharp.Instrument'),
  serialized_pb=_b('\n\x1finstrument_tag_definition.proto\x1a\x1finstrument_tag_identifier.proto\x1a#claros_i18nkey_text_reference.proto\x1a-enum_instrument_data_attribute_priority.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x9f\x02\n\x17InstrumentTagDefinition\x12,\n\nidentifier\x18\x01 \x01(\x0b\x32\x18.InstrumentTagIdentifier\x12\x39\n\x14i18nKeyTextReference\x18\x02 \x01(\x0b\x32\x1b.ClarosI18NKeyTextReference\x12\x31\n\x0bparameterId\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x30\n\nunitTypeId\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x36\n\nattributes\x18\x07 \x01(\x0b\x32\".InstrumentTagDefinitionAttributes\"\xe7\x01\n!InstrumentTagDefinitionAttributes\x12\x0f\n\x07visible\x18\x01 \x01(\x08\x12=\n\x0f\x64isplayPriority\x18\x02 \x01(\x0e\x32$.EnumInstrumentDataAttributePriority\x12\x36\n\x10\x64isplaySortOrder\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12:\n\x14\x64isplayDecimalPoints\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\"C\n\x18InstrumentTagDefinitions\x12\'\n\x05items\x18\x01 \x03(\x0b\x32\x18.InstrumentTagDefinitionB\x1f\xaa\x02\x1cONE.Models.CSharp.Instrumentb\x06proto3')
  ,
  dependencies=[instrument__tag__identifier__pb2.DESCRIPTOR,claros__i18nkey__text__reference__pb2.DESCRIPTOR,enum__instrument__data__attribute__priority__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_INSTRUMENTTAGDEFINITION = _descriptor.Descriptor(
  name='InstrumentTagDefinition',
  full_name='InstrumentTagDefinition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='InstrumentTagDefinition.identifier', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='i18nKeyTextReference', full_name='InstrumentTagDefinition.i18nKeyTextReference', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameterId', full_name='InstrumentTagDefinition.parameterId', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unitTypeId', full_name='InstrumentTagDefinition.unitTypeId', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='InstrumentTagDefinition.attributes', index=4,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=472,
)


_INSTRUMENTTAGDEFINITIONATTRIBUTES = _descriptor.Descriptor(
  name='InstrumentTagDefinitionAttributes',
  full_name='InstrumentTagDefinitionAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='visible', full_name='InstrumentTagDefinitionAttributes.visible', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='displayPriority', full_name='InstrumentTagDefinitionAttributes.displayPriority', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='displaySortOrder', full_name='InstrumentTagDefinitionAttributes.displaySortOrder', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='displayDecimalPoints', full_name='InstrumentTagDefinitionAttributes.displayDecimalPoints', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=475,
  serialized_end=706,
)


_INSTRUMENTTAGDEFINITIONS = _descriptor.Descriptor(
  name='InstrumentTagDefinitions',
  full_name='InstrumentTagDefinitions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='InstrumentTagDefinitions.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=708,
  serialized_end=775,
)

_INSTRUMENTTAGDEFINITION.fields_by_name['identifier'].message_type = instrument__tag__identifier__pb2._INSTRUMENTTAGIDENTIFIER
_INSTRUMENTTAGDEFINITION.fields_by_name['i18nKeyTextReference'].message_type = claros__i18nkey__text__reference__pb2._CLAROSI18NKEYTEXTREFERENCE
_INSTRUMENTTAGDEFINITION.fields_by_name['parameterId'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_INSTRUMENTTAGDEFINITION.fields_by_name['unitTypeId'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_INSTRUMENTTAGDEFINITION.fields_by_name['attributes'].message_type = _INSTRUMENTTAGDEFINITIONATTRIBUTES
_INSTRUMENTTAGDEFINITIONATTRIBUTES.fields_by_name['displayPriority'].enum_type = enum__instrument__data__attribute__priority__pb2._ENUMINSTRUMENTDATAATTRIBUTEPRIORITY
_INSTRUMENTTAGDEFINITIONATTRIBUTES.fields_by_name['displaySortOrder'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
_INSTRUMENTTAGDEFINITIONATTRIBUTES.fields_by_name['displayDecimalPoints'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
_INSTRUMENTTAGDEFINITIONS.fields_by_name['items'].message_type = _INSTRUMENTTAGDEFINITION
DESCRIPTOR.message_types_by_name['InstrumentTagDefinition'] = _INSTRUMENTTAGDEFINITION
DESCRIPTOR.message_types_by_name['InstrumentTagDefinitionAttributes'] = _INSTRUMENTTAGDEFINITIONATTRIBUTES
DESCRIPTOR.message_types_by_name['InstrumentTagDefinitions'] = _INSTRUMENTTAGDEFINITIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstrumentTagDefinition = _reflection.GeneratedProtocolMessageType('InstrumentTagDefinition', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUMENTTAGDEFINITION,
  '__module__' : 'instrument_tag_definition_pb2'
  # @@protoc_insertion_point(class_scope:InstrumentTagDefinition)
  })
_sym_db.RegisterMessage(InstrumentTagDefinition)

InstrumentTagDefinitionAttributes = _reflection.GeneratedProtocolMessageType('InstrumentTagDefinitionAttributes', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUMENTTAGDEFINITIONATTRIBUTES,
  '__module__' : 'instrument_tag_definition_pb2'
  # @@protoc_insertion_point(class_scope:InstrumentTagDefinitionAttributes)
  })
_sym_db.RegisterMessage(InstrumentTagDefinitionAttributes)

InstrumentTagDefinitions = _reflection.GeneratedProtocolMessageType('InstrumentTagDefinitions', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUMENTTAGDEFINITIONS,
  '__module__' : 'instrument_tag_definition_pb2'
  # @@protoc_insertion_point(class_scope:InstrumentTagDefinitions)
  })
_sym_db.RegisterMessage(InstrumentTagDefinitions)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
