# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instrument_detail_summary.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from . import instrument_manifest_summary_pb2 as instrument__manifest__summary__pb2
from . import enum_connection_status_pb2 as enum__connection__status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='instrument_detail_summary.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\034ONE.Models.CSharp.Instrument'),
  serialized_pb=_b('\n\x1finstrument_detail_summary.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a!instrument_manifest_summary.proto\x1a\x1c\x65num_connection_status.proto\"\x93\x03\n\x17InstrumentDetailSummary\x12.\n\x08\x66usionId\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x32\n\x0cinstrumentId\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x32\n\x0cserialNumber\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x36\n\x10\x65nterpriseTwinId\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x38\n\x12\x65nterpriseTwinName\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12=\n\x19instrumentManifestSummary\x18\x06 \x01(\x0b\x32\x1a.InstrumentManifestSummary\x12/\n\x10\x63onnectionStatus\x18\x07 \x01(\x0e\x32\x15.EnumConnectionStatus\"D\n\x19InstrumentDetailSummaries\x12\'\n\x05items\x18\x01 \x03(\x0b\x32\x18.InstrumentDetailSummaryB\x1f\xaa\x02\x1cONE.Models.CSharp.Instrumentb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,instrument__manifest__summary__pb2.DESCRIPTOR,enum__connection__status__pb2.DESCRIPTOR,])




_INSTRUMENTDETAILSUMMARY = _descriptor.Descriptor(
  name='InstrumentDetailSummary',
  full_name='InstrumentDetailSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fusionId', full_name='InstrumentDetailSummary.fusionId', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instrumentId', full_name='InstrumentDetailSummary.instrumentId', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serialNumber', full_name='InstrumentDetailSummary.serialNumber', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enterpriseTwinId', full_name='InstrumentDetailSummary.enterpriseTwinId', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enterpriseTwinName', full_name='InstrumentDetailSummary.enterpriseTwinName', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instrumentManifestSummary', full_name='InstrumentDetailSummary.instrumentManifestSummary', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connectionStatus', full_name='InstrumentDetailSummary.connectionStatus', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=536,
)


_INSTRUMENTDETAILSUMMARIES = _descriptor.Descriptor(
  name='InstrumentDetailSummaries',
  full_name='InstrumentDetailSummaries',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='InstrumentDetailSummaries.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=538,
  serialized_end=606,
)

_INSTRUMENTDETAILSUMMARY.fields_by_name['fusionId'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_INSTRUMENTDETAILSUMMARY.fields_by_name['instrumentId'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_INSTRUMENTDETAILSUMMARY.fields_by_name['serialNumber'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_INSTRUMENTDETAILSUMMARY.fields_by_name['enterpriseTwinId'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_INSTRUMENTDETAILSUMMARY.fields_by_name['enterpriseTwinName'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_INSTRUMENTDETAILSUMMARY.fields_by_name['instrumentManifestSummary'].message_type = instrument__manifest__summary__pb2._INSTRUMENTMANIFESTSUMMARY
_INSTRUMENTDETAILSUMMARY.fields_by_name['connectionStatus'].enum_type = enum__connection__status__pb2._ENUMCONNECTIONSTATUS
_INSTRUMENTDETAILSUMMARIES.fields_by_name['items'].message_type = _INSTRUMENTDETAILSUMMARY
DESCRIPTOR.message_types_by_name['InstrumentDetailSummary'] = _INSTRUMENTDETAILSUMMARY
DESCRIPTOR.message_types_by_name['InstrumentDetailSummaries'] = _INSTRUMENTDETAILSUMMARIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstrumentDetailSummary = _reflection.GeneratedProtocolMessageType('InstrumentDetailSummary', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUMENTDETAILSUMMARY,
  '__module__' : 'instrument_detail_summary_pb2'
  # @@protoc_insertion_point(class_scope:InstrumentDetailSummary)
  })
_sym_db.RegisterMessage(InstrumentDetailSummary)

InstrumentDetailSummaries = _reflection.GeneratedProtocolMessageType('InstrumentDetailSummaries', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUMENTDETAILSUMMARIES,
  '__module__' : 'instrument_detail_summary_pb2'
  # @@protoc_insertion_point(class_scope:InstrumentDetailSummaries)
  })
_sym_db.RegisterMessage(InstrumentDetailSummaries)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
