# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification_contact.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='notification_contact.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\021ONE.Models.CSharp'),
  serialized_pb=_b('\n\x1anotification_contact.proto\"9\n\x13NotificationContact\x12\x13\n\x0b\x43ontactType\x18\x01 \x01(\t\x12\r\n\x05Value\x18\x02 \x01(\t\";\n\x14NotificationContacts\x12#\n\x05items\x18\x01 \x03(\x0b\x32\x14.NotificationContactB\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')
)




_NOTIFICATIONCONTACT = _descriptor.Descriptor(
  name='NotificationContact',
  full_name='NotificationContact',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ContactType', full_name='NotificationContact.ContactType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Value', full_name='NotificationContact.Value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=87,
)


_NOTIFICATIONCONTACTS = _descriptor.Descriptor(
  name='NotificationContacts',
  full_name='NotificationContacts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='NotificationContacts.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=148,
)

_NOTIFICATIONCONTACTS.fields_by_name['items'].message_type = _NOTIFICATIONCONTACT
DESCRIPTOR.message_types_by_name['NotificationContact'] = _NOTIFICATIONCONTACT
DESCRIPTOR.message_types_by_name['NotificationContacts'] = _NOTIFICATIONCONTACTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotificationContact = _reflection.GeneratedProtocolMessageType('NotificationContact', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONCONTACT,
  '__module__' : 'notification_contact_pb2'
  # @@protoc_insertion_point(class_scope:NotificationContact)
  })
_sym_db.RegisterMessage(NotificationContact)

NotificationContacts = _reflection.GeneratedProtocolMessageType('NotificationContacts', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONCONTACTS,
  '__module__' : 'notification_contact_pb2'
  # @@protoc_insertion_point(class_scope:NotificationContacts)
  })
_sym_db.RegisterMessage(NotificationContacts)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
