# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: row_index.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import timewindow_pb2 as timewindow__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='row_index.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\021ONE.Models.CSharp'),
  serialized_pb=_b('\n\x0frow_index.proto\x1a\x10timewindow.proto\"\x91\x01\n\x08RowIndex\x12\n\n\x02id\x18\x01 \x01(\r\x12\x18\n\x10worksheetVersion\x18\x02 \x01(\r\x12\x1f\n\ntimeWindow\x18\x03 \x01(\x0b\x32\x0b.TimeWindow\x12\x11\n\tisInSpeed\x18\x05 \x01(\x08\x12\x13\n\x0bisRowCooked\x18\x06 \x01(\x08\x12\x16\n\x0eisColumnCooked\x18\x07 \x01(\x08\"l\n\nRowIndices\x12%\n\x05items\x18\x01 \x03(\x0b\x32\x16.RowIndices.ItemsEntry\x1a\x37\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.RowIndex:\x02\x38\x01\x42\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')
  ,
  dependencies=[timewindow__pb2.DESCRIPTOR,])




_ROWINDEX = _descriptor.Descriptor(
  name='RowIndex',
  full_name='RowIndex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RowIndex.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worksheetVersion', full_name='RowIndex.worksheetVersion', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeWindow', full_name='RowIndex.timeWindow', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isInSpeed', full_name='RowIndex.isInSpeed', index=3,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isRowCooked', full_name='RowIndex.isRowCooked', index=4,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isColumnCooked', full_name='RowIndex.isColumnCooked', index=5,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=183,
)


_ROWINDICES_ITEMSENTRY = _descriptor.Descriptor(
  name='ItemsEntry',
  full_name='RowIndices.ItemsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='RowIndices.ItemsEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='RowIndices.ItemsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=293,
)

_ROWINDICES = _descriptor.Descriptor(
  name='RowIndices',
  full_name='RowIndices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='RowIndices.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ROWINDICES_ITEMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=293,
)

_ROWINDEX.fields_by_name['timeWindow'].message_type = timewindow__pb2._TIMEWINDOW
_ROWINDICES_ITEMSENTRY.fields_by_name['value'].message_type = _ROWINDEX
_ROWINDICES_ITEMSENTRY.containing_type = _ROWINDICES
_ROWINDICES.fields_by_name['items'].message_type = _ROWINDICES_ITEMSENTRY
DESCRIPTOR.message_types_by_name['RowIndex'] = _ROWINDEX
DESCRIPTOR.message_types_by_name['RowIndices'] = _ROWINDICES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RowIndex = _reflection.GeneratedProtocolMessageType('RowIndex', (_message.Message,), {
  'DESCRIPTOR' : _ROWINDEX,
  '__module__' : 'row_index_pb2'
  # @@protoc_insertion_point(class_scope:RowIndex)
  })
_sym_db.RegisterMessage(RowIndex)

RowIndices = _reflection.GeneratedProtocolMessageType('RowIndices', (_message.Message,), {

  'ItemsEntry' : _reflection.GeneratedProtocolMessageType('ItemsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ROWINDICES_ITEMSENTRY,
    '__module__' : 'row_index_pb2'
    # @@protoc_insertion_point(class_scope:RowIndices.ItemsEntry)
    })
  ,
  'DESCRIPTOR' : _ROWINDICES,
  '__module__' : 'row_index_pb2'
  # @@protoc_insertion_point(class_scope:RowIndices)
  })
_sym_db.RegisterMessage(RowIndices)
_sym_db.RegisterMessage(RowIndices.ItemsEntry)


DESCRIPTOR._options = None
_ROWINDICES_ITEMSENTRY._options = None
# @@protoc_insertion_point(module_scope)
