# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_tech_tenant_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import jsonTicksDateTime_pb2 as jsonTicksDateTime__pb2
from . import record_auditinfo_pb2 as record__auditinfo__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_tech_tenant_request.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\021ONE.Models.CSharp'),
  serialized_pb=_b('\n!service_tech_tenant_request.proto\x1a\x17jsonTicksDateTime.proto\x1a\x16record_auditinfo.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a google/protobuf/field_mask.proto\"\x9a\x02\n\x18ServiceTechTenantRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08tenantId\x18\x02 \x01(\t\x12\x0e\n\x06userId\x18\x03 \x01(\t\x12\x19\n\x11serviceTechUserId\x18\x04 \x01(\t\x12\x33\n\ri18NStatusKey\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12%\n\texpiresOn\x18\x06 \x01(\x0b\x32\x12.JsonTicksDateTime\x12.\n\nupdateMask\x18\x62 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\x12)\n\x0frecordAuditInfo\x18\x63 \x01(\x0b\x32\x10.RecordAuditInfo\"E\n\x19ServiceTechTenantRequests\x12(\n\x05items\x18\x01 \x03(\x0b\x32\x19.ServiceTechTenantRequestB\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')
  ,
  dependencies=[jsonTicksDateTime__pb2.DESCRIPTOR,record__auditinfo__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,google_dot_protobuf_dot_field__mask__pb2.DESCRIPTOR,])




_SERVICETECHTENANTREQUEST = _descriptor.Descriptor(
  name='ServiceTechTenantRequest',
  full_name='ServiceTechTenantRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ServiceTechTenantRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tenantId', full_name='ServiceTechTenantRequest.tenantId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userId', full_name='ServiceTechTenantRequest.userId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceTechUserId', full_name='ServiceTechTenantRequest.serviceTechUserId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='i18NStatusKey', full_name='ServiceTechTenantRequest.i18NStatusKey', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expiresOn', full_name='ServiceTechTenantRequest.expiresOn', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updateMask', full_name='ServiceTechTenantRequest.updateMask', index=6,
      number=98, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recordAuditInfo', full_name='ServiceTechTenantRequest.recordAuditInfo', index=7,
      number=99, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=435,
)


_SERVICETECHTENANTREQUESTS = _descriptor.Descriptor(
  name='ServiceTechTenantRequests',
  full_name='ServiceTechTenantRequests',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='ServiceTechTenantRequests.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=506,
)

_SERVICETECHTENANTREQUEST.fields_by_name['i18NStatusKey'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_SERVICETECHTENANTREQUEST.fields_by_name['expiresOn'].message_type = jsonTicksDateTime__pb2._JSONTICKSDATETIME
_SERVICETECHTENANTREQUEST.fields_by_name['updateMask'].message_type = google_dot_protobuf_dot_field__mask__pb2._FIELDMASK
_SERVICETECHTENANTREQUEST.fields_by_name['recordAuditInfo'].message_type = record__auditinfo__pb2._RECORDAUDITINFO
_SERVICETECHTENANTREQUESTS.fields_by_name['items'].message_type = _SERVICETECHTENANTREQUEST
DESCRIPTOR.message_types_by_name['ServiceTechTenantRequest'] = _SERVICETECHTENANTREQUEST
DESCRIPTOR.message_types_by_name['ServiceTechTenantRequests'] = _SERVICETECHTENANTREQUESTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServiceTechTenantRequest = _reflection.GeneratedProtocolMessageType('ServiceTechTenantRequest', (_message.Message,), {
  'DESCRIPTOR' : _SERVICETECHTENANTREQUEST,
  '__module__' : 'service_tech_tenant_request_pb2'
  # @@protoc_insertion_point(class_scope:ServiceTechTenantRequest)
  })
_sym_db.RegisterMessage(ServiceTechTenantRequest)

ServiceTechTenantRequests = _reflection.GeneratedProtocolMessageType('ServiceTechTenantRequests', (_message.Message,), {
  'DESCRIPTOR' : _SERVICETECHTENANTREQUESTS,
  '__module__' : 'service_tech_tenant_request_pb2'
  # @@protoc_insertion_point(class_scope:ServiceTechTenantRequests)
  })
_sym_db.RegisterMessage(ServiceTechTenantRequests)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
