# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tenant.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from . import enum_timezone_pb2 as enum__timezone__pb2
from . import record_auditinfo_pb2 as record__auditinfo__pb2
from . import product_offering_pb2 as product__offering__pb2
from . import service_tech_tenant_request_pb2 as service__tech__tenant__request__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tenant.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\021ONE.Models.CSharp'),
  serialized_pb=_b('\n\x0ctenant.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a google/protobuf/field_mask.proto\x1a\x13\x65num_timezone.proto\x1a\x16record_auditinfo.proto\x1a\x16product_offering.proto\x1a!service_tech_tenant_request.proto\"\x8b\x03\n\x06Tenant\x12\n\n\x02id\x18\x01 \x01(\t\x12*\n\x04name\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12-\n\x07\x63ulture\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12#\n\x0c\x65numTimeZone\x18\x04 \x01(\x0e\x32\r.EnumTimeZone\x12*\n\x10productOfferings\x18\x05 \x03(\x0b\x32\x10.ProductOffering\x12<\n\x19serviceTechTenantRequests\x18\x07 \x03(\x0b\x32\x19.ServiceTechTenantRequest\x12\x30\n\nchargifyId\x18\x08 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12.\n\nupdateMask\x18\x62 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\x12)\n\x0frecordAuditInfo\x18\x63 \x01(\x0b\x32\x10.RecordAuditInfo\"!\n\x07Tenants\x12\x16\n\x05items\x18\x01 \x03(\x0b\x32\x07.TenantB\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,google_dot_protobuf_dot_field__mask__pb2.DESCRIPTOR,enum__timezone__pb2.DESCRIPTOR,record__auditinfo__pb2.DESCRIPTOR,product__offering__pb2.DESCRIPTOR,service__tech__tenant__request__pb2.DESCRIPTOR,])




_TENANT = _descriptor.Descriptor(
  name='Tenant',
  full_name='Tenant',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Tenant.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Tenant.name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='culture', full_name='Tenant.culture', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enumTimeZone', full_name='Tenant.enumTimeZone', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='productOfferings', full_name='Tenant.productOfferings', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceTechTenantRequests', full_name='Tenant.serviceTechTenantRequests', index=5,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chargifyId', full_name='Tenant.chargifyId', index=6,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updateMask', full_name='Tenant.updateMask', index=7,
      number=98, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recordAuditInfo', full_name='Tenant.recordAuditInfo', index=8,
      number=99, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=582,
)


_TENANTS = _descriptor.Descriptor(
  name='Tenants',
  full_name='Tenants',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='Tenants.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=584,
  serialized_end=617,
)

_TENANT.fields_by_name['name'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_TENANT.fields_by_name['culture'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_TENANT.fields_by_name['enumTimeZone'].enum_type = enum__timezone__pb2._ENUMTIMEZONE
_TENANT.fields_by_name['productOfferings'].message_type = product__offering__pb2._PRODUCTOFFERING
_TENANT.fields_by_name['serviceTechTenantRequests'].message_type = service__tech__tenant__request__pb2._SERVICETECHTENANTREQUEST
_TENANT.fields_by_name['chargifyId'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_TENANT.fields_by_name['updateMask'].message_type = google_dot_protobuf_dot_field__mask__pb2._FIELDMASK
_TENANT.fields_by_name['recordAuditInfo'].message_type = record__auditinfo__pb2._RECORDAUDITINFO
_TENANTS.fields_by_name['items'].message_type = _TENANT
DESCRIPTOR.message_types_by_name['Tenant'] = _TENANT
DESCRIPTOR.message_types_by_name['Tenants'] = _TENANTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tenant = _reflection.GeneratedProtocolMessageType('Tenant', (_message.Message,), {
  'DESCRIPTOR' : _TENANT,
  '__module__' : 'tenant_pb2'
  # @@protoc_insertion_point(class_scope:Tenant)
  })
_sym_db.RegisterMessage(Tenant)

Tenants = _reflection.GeneratedProtocolMessageType('Tenants', (_message.Message,), {
  'DESCRIPTOR' : _TENANTS,
  '__module__' : 'tenant_pb2'
  # @@protoc_insertion_point(class_scope:Tenants)
  })
_sym_db.RegisterMessage(Tenants)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
