# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_analyte_group.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from . import record_auditinfo_pb2 as record__auditinfo__pb2
from . import analyte_pb2 as analyte__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='test_analyte_group.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\021ONE.Models.CSharp'),
  serialized_pb=_b('\n\x18test_analyte_group.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x16record_auditinfo.proto\x1a\ranalyte.proto\"\xb0\x02\n\x10TestAnalyteGroup\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\rauthTwinRefId\x18\x03 \x01(\t\x12\x31\n\x0bpropertyBag\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x32\n\x0cuiDefinition\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12+\n\x05notes\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x10\n\x08isActive\x18\x07 \x01(\x08\x12\x1a\n\x08\x61nalytes\x18\x08 \x03(\x0b\x32\x08.Analyte\x12)\n\x0frecordAuditInfo\x18\x63 \x01(\x0b\x32\x10.RecordAuditInfo\"5\n\x11TestAnalyteGroups\x12 \n\x05items\x18\x01 \x03(\x0b\x32\x11.TestAnalyteGroupB\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,record__auditinfo__pb2.DESCRIPTOR,analyte__pb2.DESCRIPTOR,])




_TESTANALYTEGROUP = _descriptor.Descriptor(
  name='TestAnalyteGroup',
  full_name='TestAnalyteGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TestAnalyteGroup.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='TestAnalyteGroup.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authTwinRefId', full_name='TestAnalyteGroup.authTwinRefId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='propertyBag', full_name='TestAnalyteGroup.propertyBag', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uiDefinition', full_name='TestAnalyteGroup.uiDefinition', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notes', full_name='TestAnalyteGroup.notes', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isActive', full_name='TestAnalyteGroup.isActive', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='analytes', full_name='TestAnalyteGroup.analytes', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recordAuditInfo', full_name='TestAnalyteGroup.recordAuditInfo', index=8,
      number=99, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=404,
)


_TESTANALYTEGROUPS = _descriptor.Descriptor(
  name='TestAnalyteGroups',
  full_name='TestAnalyteGroups',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='TestAnalyteGroups.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=459,
)

_TESTANALYTEGROUP.fields_by_name['propertyBag'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_TESTANALYTEGROUP.fields_by_name['uiDefinition'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_TESTANALYTEGROUP.fields_by_name['notes'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_TESTANALYTEGROUP.fields_by_name['analytes'].message_type = analyte__pb2._ANALYTE
_TESTANALYTEGROUP.fields_by_name['recordAuditInfo'].message_type = record__auditinfo__pb2._RECORDAUDITINFO
_TESTANALYTEGROUPS.fields_by_name['items'].message_type = _TESTANALYTEGROUP
DESCRIPTOR.message_types_by_name['TestAnalyteGroup'] = _TESTANALYTEGROUP
DESCRIPTOR.message_types_by_name['TestAnalyteGroups'] = _TESTANALYTEGROUPS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestAnalyteGroup = _reflection.GeneratedProtocolMessageType('TestAnalyteGroup', (_message.Message,), {
  'DESCRIPTOR' : _TESTANALYTEGROUP,
  '__module__' : 'test_analyte_group_pb2'
  # @@protoc_insertion_point(class_scope:TestAnalyteGroup)
  })
_sym_db.RegisterMessage(TestAnalyteGroup)

TestAnalyteGroups = _reflection.GeneratedProtocolMessageType('TestAnalyteGroups', (_message.Message,), {
  'DESCRIPTOR' : _TESTANALYTEGROUPS,
  '__module__' : 'test_analyte_group_pb2'
  # @@protoc_insertion_point(class_scope:TestAnalyteGroups)
  })
_sym_db.RegisterMessage(TestAnalyteGroups)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
