
#ifndef VTKSERIALIZATIONMANAGER_EXPORT_H
#define VTKSERIALIZATIONMANAGER_EXPORT_H

#ifdef VTKSERIALIZATIONMANAGER_STATIC_DEFINE
#  define VTKSERIALIZATIONMANAGER_EXPORT
#  define VTKSERIALIZATIONMANAGER_NO_EXPORT
#else
#  ifndef VTKSERIALIZATIONMANAGER_EXPORT
#    ifdef SerializationManager_EXPORTS
        /* We are building this library */
#      define VTKSERIALIZATIONMANAGER_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define VTKSERIALIZATIONMANAGER_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef VTKSERIALIZATIONMANAGER_NO_EXPORT
#    define VTKSERIALIZATIONMANAGER_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef VTKSERIALIZATIONMANAGER_DEPRECATED
#  define VTKSERIALIZATIONMANAGER_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef VTKSERIALIZATIONMANAGER_DEPRECATED_EXPORT
#  define VTKSERIALIZATIONMANAGER_DEPRECATED_EXPORT VTKSERIALIZATIONMANAGER_EXPORT VTKSERIALIZATIONMANAGER_DEPRECATED
#endif

#ifndef VTKSERIALIZATIONMANAGER_DEPRECATED_NO_EXPORT
#  define VTKSERIALIZATIONMANAGER_DEPRECATED_NO_EXPORT VTKSERIALIZATIONMANAGER_NO_EXPORT VTKSERIALIZATIONMANAGER_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKSERIALIZATIONMANAGER_NO_DEPRECATED
#    define VTKSERIALIZATIONMANAGER_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkSerializationManagerModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKSERIALIZATIONMANAGER_EXPORT_H */
