
#ifndef VTKTESTINGSERIALIZATION_EXPORT_H
#define VTKTESTINGSERIALIZATION_EXPORT_H

#ifdef VTKTESTINGSERIALIZATION_STATIC_DEFINE
#  define VTKTESTINGSERIALIZATION_EXPORT
#  define VTKTESTINGSERIALIZATION_NO_EXPORT
#else
#  ifndef VTKTESTINGSERIALIZATION_EXPORT
#    ifdef TestingSerialization_EXPORTS
        /* We are building this library */
#      define VTKTESTINGSERIALIZATION_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define VTKTESTINGSERIALIZATION_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef VTKTESTINGSERIALIZATION_NO_EXPORT
#    define VTKTESTINGSERIALIZATION_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef VTKTESTINGSERIALIZATION_DEPRECATED
#  define VTKTESTINGSERIALIZATION_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef VTKTESTINGSERIALIZATION_DEPRECATED_EXPORT
#  define VTKTESTINGSERIALIZATION_DEPRECATED_EXPORT VTKTESTINGSERIALIZATION_EXPORT VTKTESTINGSERIALIZATION_DEPRECATED
#endif

#ifndef VTKTESTINGSERIALIZATION_DEPRECATED_NO_EXPORT
#  define VTKTESTINGSERIALIZATION_DEPRECATED_NO_EXPORT VTKTESTINGSERIALIZATION_NO_EXPORT VTKTESTINGSERIALIZATION_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKTESTINGSERIALIZATION_NO_DEPRECATED
#    define VTKTESTINGSERIALIZATION_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkTestingSerializationModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKTESTINGSERIALIZATION_EXPORT_H */
