"""Blog-related MCP Prompts for Halo."""

from mcp.types import Prompt, PromptArgument

BLOG_PROMPTS = [
    Prompt(
        name="halo_blog_writing_assistant",
        description="博客写作助手 - 帮助创建高质量的博客文章",
        arguments=[
            PromptArgument(
                name="topic",
                description="文章主题或标题",
                required=True,
            ),
            PromptArgument(
                name="target_audience",
                description="目标读者群体（如：技术开发者、产品经理、普通用户等）",
                required=False,
            ),
            PromptArgument(
                name="article_type",
                description="文章类型（如：教程、经验分享、技术解析、产品介绍等）",
                required=False,
            ),
            PromptArgument(
                name="word_count",
                description="期望字数（如：1000、2000、3000等）",
                required=False,
            ),
            PromptArgument(
                name="tone",
                description="写作风格（如：专业、轻松、幽默、严肃等）",
                required=False,
            ),
        ],
    ),
    Prompt(
        name="halo_content_optimizer",
        description="内容优化助手 - 优化现有文章的结构、可读性和吸引力",
        arguments=[
            PromptArgument(
                name="content",
                description="需要优化的文章内容",
                required=True,
            ),
            PromptArgument(
                name="optimization_focus",
                description="优化重点（如：可读性、结构、吸引力、专业性等）",
                required=False,
            ),
            PromptArgument(
                name="target_length",
                description="目标长度（如：扩展、压缩、保持不变）",
                required=False,
            ),
        ],
    ),
    Prompt(
        name="halo_seo_optimizer",
        description="SEO 优化助手 - 优化文章的搜索引擎可见性",
        arguments=[
            PromptArgument(
                name="title",
                description="文章标题",
                required=True,
            ),
            PromptArgument(
                name="content",
                description="文章内容",
                required=True,
            ),
            PromptArgument(
                name="target_keywords",
                description="目标关键词（用逗号分隔）",
                required=False,
            ),
            PromptArgument(
                name="meta_description_length",
                description="元描述长度限制（默认：160字符）",
                required=False,
            ),
        ],
    ),
    Prompt(
        name="halo_title_generator",
        description="标题生成器 - 为文章生成吸引人的标题",
        arguments=[
            PromptArgument(
                name="content_summary",
                description="文章内容摘要或主要观点",
                required=True,
            ),
            PromptArgument(
                name="title_style",
                description="标题风格（如：问题式、数字式、对比式、悬念式等）",
                required=False,
            ),
            PromptArgument(
                name="title_count",
                description="生成标题数量（默认：5个）",
                required=False,
            ),
        ],
    ),
    Prompt(
        name="halo_excerpt_generator",
        description="摘要生成器 - 为文章生成简洁有效的摘要",
        arguments=[
            PromptArgument(
                name="content",
                description="文章完整内容",
                required=True,
            ),
            PromptArgument(
                name="excerpt_length",
                description="摘要长度（如：短、中、长，或具体字数）",
                required=False,
            ),
            PromptArgument(
                name="excerpt_style",
                description="摘要风格（如：概述式、亮点式、问题式等）",
                required=False,
            ),
        ],
    ),
    Prompt(
        name="halo_tag_suggester",
        description="标签建议器 - 根据文章内容推荐合适的标签",
        arguments=[
            PromptArgument(
                name="title",
                description="文章标题",
                required=True,
            ),
            PromptArgument(
                name="content",
                description="文章内容",
                required=True,
            ),
            PromptArgument(
                name="existing_tags",
                description="现有标签列表（用逗号分隔），用于参考和避免重复",
                required=False,
            ),
            PromptArgument(
                name="tag_count",
                description="建议标签数量（默认：5-8个）",
                required=False,
            ),
        ],
    ),
    Prompt(
        name="halo_category_suggester",
        description="分类建议器 - 根据文章内容推荐合适的分类",
        arguments=[
            PromptArgument(
                name="title",
                description="文章标题",
                required=True,
            ),
            PromptArgument(
                name="content",
                description="文章内容",
                required=True,
            ),
            PromptArgument(
                name="existing_categories",
                description="现有分类列表（用逗号分隔），用于选择最合适的分类",
                required=False,
            ),
        ],
    ),
    Prompt(
        name="halo_content_translator",
        description="内容翻译助手 - 翻译文章内容并保持格式和风格",
        arguments=[
            PromptArgument(
                name="content",
                description="需要翻译的内容",
                required=True,
            ),
            PromptArgument(
                name="target_language",
                description="目标语言（如：英文、日文、韩文等）",
                required=True,
            ),
            PromptArgument(
                name="preserve_formatting",
                description="是否保持 Markdown 格式（默认：是）",
                required=False,
            ),
            PromptArgument(
                name="translation_style",
                description="翻译风格（如：直译、意译、本地化等）",
                required=False,
            ),
        ],
    ),
    Prompt(
        name="halo_content_proofreader",
        description="内容校对助手 - 检查和修正文章的语法、拼写和表达",
        arguments=[
            PromptArgument(
                name="content",
                description="需要校对的内容",
                required=True,
            ),
            PromptArgument(
                name="language",
                description="内容语言（如：中文、英文等）",
                required=False,
            ),
            PromptArgument(
                name="check_focus",
                description="校对重点（如：语法、拼写、表达、逻辑等）",
                required=False,
            ),
        ],
    ),
    Prompt(
        name="halo_series_planner",
        description="系列文章规划助手 - 规划和组织系列文章的结构和内容",
        arguments=[
            PromptArgument(
                name="series_topic",
                description="系列文章主题",
                required=True,
            ),
            PromptArgument(
                name="target_audience",
                description="目标读者群体",
                required=False,
            ),
            PromptArgument(
                name="article_count",
                description="计划文章数量",
                required=False,
            ),
            PromptArgument(
                name="difficulty_progression",
                description="难度递进方式（如：由浅入深、并列展开等）",
                required=False,
            ),
        ],
    ),
]