from typing import Any, Dict, List, Optional, Tuple, Union

from com.inductiveautomation.factorypmi.application import FPMIApp, FPMIWindow
from com.inductiveautomation.factorypmi.application.script import PyComponentWrapper
from com.inductiveautomation.ignition.common.i18n.keyboard import KeyboardLayout
from com.inductiveautomation.ignition.common.model.values import QualityCode
from dev.coatl.helper.types import AnyStr
from java.awt import Color, Component, Graphics
from java.awt.event import ActionEvent, ComponentEvent, MouseEvent
from java.awt.image import BufferedImage
from java.awt.print import PageFormat
from java.lang import Number, Object
from java.util import EventObject, Locale
from javax.swing import JComponent, JFrame, JPopupMenu
from org.python.core import PyObject, PySequence, PyTuple

class INavUtilities:
    def centerWindow(self, arg: Union[FPMIWindow, AnyStr]) -> None: ...
    def closeParentWindow(self, event: EventObject) -> None: ...
    def closeWindow(self, arg: Union[FPMIWindow, AnyStr]) -> None: ...
    def getCurrentWindow(self) -> AnyStr: ...
    def goBack(self) -> PyObject: ...
    def goForward(self) -> PyObject: ...
    def goHome(self) -> PyObject: ...
    def openWindow(
        self, path: AnyStr, params: Optional[Dict[AnyStr, Any]] = ...
    ) -> PyObject: ...
    def openWindowImpl(
        self, path: AnyStr, params: Dict[AnyStr, Any], openAdditional: bool
    ) -> PyObject: ...
    def openWindowInstance(
        self, path: AnyStr, params: Optional[Dict[AnyStr, Any]] = ...
    ) -> PyObject: ...
    def swapTo(self, name: AnyStr, params: Dict[AnyStr, Any]) -> PyObject: ...
    def swapWindow(self, *args: Any) -> PyObject: ...

class ClientDatasetUtilities(Object):
    def __init__(self, app: FPMIApp) -> None: ...

class ClientSystemUtilities(Object):
    def __init__(self) -> None: ...

class NavUtilities(INavUtilities):
    def centerWindow(self, arg: Union[FPMIWindow, AnyStr]) -> None: ...
    def closeParentWindow(self, event: EventObject) -> None: ...
    def closeWindow(self, arg: Union[FPMIWindow, AnyStr]) -> None: ...
    def getCurrentWindow(self) -> AnyStr: ...
    def goBack(self) -> PyObject: ...
    def goForward(self) -> PyObject: ...
    def goHome(self) -> PyObject: ...
    def openWindow(
        self, path: AnyStr, params: Optional[Dict[AnyStr, Any]] = ...
    ) -> PyObject: ...
    def openWindowImpl(
        self, path: AnyStr, params: Dict[AnyStr, Any], openAdditional: bool
    ) -> PyObject: ...
    def openWindowInstance(
        self, path: AnyStr, params: Optional[Dict[AnyStr, Any]] = ...
    ) -> PyObject: ...
    def swapTo(self, name: AnyStr, params: Dict[AnyStr, Any]) -> PyObject: ...
    def swapWindow(self, *args: Any) -> PyObject: ...

class ClientPrintUtilities(Object):
    class ComponentPrinter(Object):
        def __init__(self, c: Component, fit: bool, zoom: float) -> None: ...
        def print(self, g: Graphics, pageFormat: PageFormat, pageIndex: int) -> int: ...

    class JythonPrintJob(Object):
        def __init__(self, c: Component) -> None: ...
        def getBottomMargin(self) -> float: ...
        def getLeftMargin(self) -> float: ...
        def getOrientation(self) -> int: ...
        def getPageHeight(self) -> float: ...
        def getPageWidth(self) -> float: ...
        def getPrinterName(self) -> AnyStr: ...
        def getRightMargin(self) -> float: ...
        def getTopMargin(self) -> float: ...
        def getZoomFactor(self) -> float: ...
        def isFitToPage(self) -> bool: ...
        def isShowPrintDialog(self) -> bool: ...
        def setBottomMargin(self, bottomMargin: float) -> None: ...
        def setFitToPage(self, fitToPage: bool) -> None: ...
        def setLeftMargin(self, leftMargin: float) -> None: ...
        def setMargins(self, m: float) -> None: ...
        def setOrientation(self, orientation: int) -> None: ...
        def setPageHeight(self, pageHeight: float) -> None: ...
        def setPageWidth(self, pageWidth: float) -> None: ...
        def setPrinterName(self, printerName: AnyStr) -> None: ...
        def setRightMargin(self, rightMargin: float) -> None: ...
        def setShowPrintDialog(self, showPrintDialog: bool) -> None: ...
        def setZoomFactor(self, zoomFactor: float) -> None: ...

    def __init__(self, app: Any) -> None: ...
    def createImage(self, c: Component) -> BufferedImage: ...
    def createPrintJob(self, c: Component) -> ClientPrintUtilities.JythonPrintJob: ...
    def printToImage(self, c: Component, fileName: Optional[str] = ...) -> None: ...

class VisionUtilities(Object):
    def __init__(self, *args: Any) -> None: ...
    def beep(self) -> None: ...
    def centerWindow(self, win: PyObject) -> None: ...
    def close(self) -> None: ...
    def closeDesktop(self, handle: AnyStr) -> None: ...
    def closeParentWindow(self, event: EventObject) -> None: ...
    def closeWindow(self, win: PyObject) -> None: ...
    def color(self, *args: Any, **kwargs: Any) -> Color: ...
    def createImage(self, c: Component) -> BufferedImage: ...
    def createPopupMenu(
        self, keys: PySequence, functions: PySequence
    ) -> JPopupMenu: ...
    def createPrintJob(self, c: Component) -> ClientPrintUtilities.JythonPrintJob: ...
    def desktop(self, arg: Union[int, AnyStr, None] = ...) -> VisionUtilities: ...
    def exit(self) -> None: ...
    def exportCSV(self, *args: Any, **kwargs: Any) -> AnyStr: ...
    def exportExcel(self, *args: Any, **kwargs: Any) -> AnyStr: ...
    def exportHTML(self, *args: Any, **kwargs: Any) -> AnyStr: ...
    def findWindow(self, path: AnyStr) -> List[PyComponentWrapper]: ...
    def getAvailableLocales(self) -> List[AnyStr]: ...
    def getAvailableTerms(self) -> List[AnyStr]: ...
    def getClientId(self) -> AnyStr: ...
    def getConnectionMode(self) -> int: ...
    def getConnectTimeout(self) -> int: ...
    def getCurrentDesktop(self) -> AnyStr: ...
    def getCurrentWindow(self) -> AnyStr: ...
    def getDesktopHandles(self) -> List[Any]: ...
    def getEdition(self) -> AnyStr: ...
    def getExternalIpAddress(self) -> AnyStr: ...
    def getGatewayAddress(self) -> AnyStr: ...
    def getHandle(self) -> AnyStr: ...
    def getInactivitySeconds(self) -> int: ...
    def getKeyboardLayouts(self) -> List[KeyboardLayout]: ...
    def getLocale(self) -> AnyStr: ...
    def getOpenedWindowNames(self) -> PyTuple: ...
    def getOpenedWindows(self) -> PyTuple: ...
    def getParentWindow(self, event: EventObject) -> PyObject: ...
    def getReadTimeout(self) -> int: ...
    def getRoles(self) -> List[AnyStr]: ...
    def getScreenIndex(self) -> int: ...
    def getScreens(self) -> PySequence: ...
    def getSibling(self, event: EventObject, name: AnyStr) -> PyObject: ...
    def getSystemFlags(self) -> int: ...
    def getUsername(self) -> AnyStr: ...
    def getUserRoles(self, *args: Any, **kwargs: Any) -> List[AnyStr]: ...
    def getWindow(self, name: AnyStr) -> PyObject: ...
    def getWindowNames(self) -> PyTuple: ...
    def goBack(self) -> PyObject: ...
    def goForward(self) -> PyObject: ...
    def goHome(self) -> PyObject: ...
    def invokeLater(self, *args: Any, **kwargs: Any) -> None: ...
    def isOverlaysEnabled(self) -> bool: ...
    def isScreenLocked(self) -> bool: ...
    def isTouchscreenMode(self) -> bool: ...
    def lockScreen(self, obscure: bool = ...) -> None: ...
    def logout(self) -> None: ...
    def openDesktop(self, *args: PyObject, **kwargs: AnyStr) -> JFrame: ...
    def openFile(self, *args: Any, **kwargs: Any) -> AnyStr: ...
    def openFiles(self, *args: Any, **kwargs: Any) -> List[AnyStr]: ...
    def openURL(self, url: AnyStr) -> None: ...
    def openWindow(
        self, path: AnyStr, params: Optional[Dict[AnyStr, Any]] = ...
    ) -> PyObject: ...
    def openWindowInstance(
        self, path: AnyStr, params: Optional[Dict[AnyStr, Any]] = ...
    ) -> PyObject: ...
    def playSoundClip(self, *args: Any, **kwargs: Any) -> None: ...
    def printToImage(self, *args: Any, **kwargs: Any) -> None: ...
    def refreshBinding(self, comp: JComponent, propName: AnyStr) -> bool: ...
    def retarget(self, *args: Any, **kwargs: Any) -> None: ...
    def saveFile(self, *args: Any, **kwargs: Any) -> AnyStr: ...
    def setConnectionMode(self, mode: int) -> None: ...
    def setConnectTimeout(self, timeout: int) -> None: ...
    def setLocale(self, locale: Union[AnyStr, Locale]) -> None: ...
    def setOverlaysEnabled(self, b: bool) -> None: ...
    def setReadTimeout(self, timeout: int) -> None: ...
    def setScreenIndex(self, index: int) -> None: ...
    def setTouchscreenMode(self, b: bool) -> None: ...
    def showColorInput(self, *args: Any, **kwargs: Any) -> Color: ...
    def showConfirm(self, *args: Any, **kwargs: Any) -> bool: ...
    def showDiagnostics(self) -> None: ...
    def showError(self, *args: Any, **kwargs: Any) -> None: ...
    def showInput(self, *args: Any, **kwargs: Any) -> Optional[AnyStr]: ...
    def showMessage(self, *args: Any, **kwargs: Any) -> None: ...
    def showNumericKeyPad(self, *args: Any, **kwargs: Any) -> Number: ...
    def showPasswordInput(self, *args: Any, **kwargs: Any) -> Optional[AnyStr]: ...
    def showTouchscreenKeyboard(self, *args: Any, **kwargs: Any) -> AnyStr: ...
    def showWarning(self, *args: Any, **kwargs: Any) -> None: ...
    def swapTo(
        self, name: AnyStr, params: Optional[Dict[AnyStr, Any]] = ...
    ) -> PyObject: ...
    def swapWindow(self, *args: Any) -> PyObject: ...
    def switchUser(self, *args: Any, **kwargs: Any) -> bool: ...
    def transform(self, *args: Any, **kwargs: AnyStr) -> PyObject: ...
    def unlockScreen(self) -> None: ...
    def updateProject(self) -> None: ...
    def validateUser(self, *args: Any, **kwargs: Any) -> bool: ...

class WindowUtilities(Object):
    class JyPopupMenu(JPopupMenu):
        def actionPerformed(self, e: ActionEvent) -> None: ...
        def addJyFunction(self, name: AnyStr, fun: PyObject) -> None: ...
        def show(self, me: Union[ComponentEvent, MouseEvent], *args: int) -> None: ...

    class PopupContext(Object):
        def endPopup(self) -> None: ...
        def startPopup(self) -> None: ...

    ACCL_NONE: int
    ACCL_CONSTANT: int
    ACCL_FAST_TO_SLOW: int
    ACCL_SLOW_TO_FAST: int
    ACCL_EASE: int
    COORD_DESIGNER: int
    COORD_SCREEN: int
    def chooseColor(
        self, initialColor: Color, dialogTitle: Optional[AnyStr] = ...
    ) -> Color: ...
    def closeDesktop(self, handle: AnyStr) -> None: ...
    @staticmethod
    def color(*args: Any) -> Color: ...
    def confirm(
        self, message: AnyStr, title: AnyStr = ..., allowCancel: bool = ...
    ) -> Optional[bool]: ...
    @staticmethod
    def convertPointToScreen(x: int, y: int, event: EventObject) -> Tuple[int, int]: ...
    @staticmethod
    def createPopupContext() -> WindowUtilities.PopupContext: ...
    @staticmethod
    def createPopupMenu(key: PySequence, functions: PySequence) -> JPopupMenu: ...
    def desktop(self, arg: Union[int, AnyStr]) -> WindowUtilities: ...
    def errorBox(self, message: AnyStr, title: Optional[AnyStr] = ...) -> None: ...
    @staticmethod
    def find(component: JComponent) -> WindowUtilities: ...
    def findWindow(self, path: AnyStr) -> List[PyComponentWrapper]: ...
    def getCurrentDesktop(self) -> AnyStr: ...
    def getDesktopHandles(self) -> PySequence: ...
    def getOpenedWindowNames(self) -> PyTuple: ...
    def getOpenedWindows(self) -> PyTuple: ...
    @staticmethod
    def getParentWindow(event: EventObject) -> PyObject: ...
    def getQuality(self, comp: JComponent, propertyName: AnyStr) -> QualityCode: ...
    def getScreenIndex(self) -> int: ...
    @staticmethod
    def getScreens() -> PySequence: ...
    @staticmethod
    def getSibling(event: EventObject, name: AnyStr) -> PyObject: ...
    def getWindow(self, name: AnyStr) -> PyObject: ...
    def getWindowNames(self) -> PyTuple: ...
    def inputBox(
        self, message: AnyStr, defaultTxt: AnyStr = ...
    ) -> Optional[AnyStr]: ...
    def isTouchscreenModeEnabled(self) -> bool: ...
    def messageBox(self, message: AnyStr, title: AnyStr = ...) -> None: ...
    def openDesktop(self, *args: PyObject, **kwargs: AnyStr) -> JFrame: ...
    def openDiagnostics(self) -> None: ...
    def passwordBox(
        self, message: AnyStr, title: AnyStr = ..., echoChar: AnyStr = ...
    ) -> Optional[AnyStr]: ...
    def setTouchScreenModeEnabled(self, b: bool) -> None: ...
    def showNumericKeyPad(
        self,
        initialValue: Number,
        fontSize: Optional[int] = ...,
        usePasswordMode: bool = ...,
    ) -> Number: ...
    def showTouchscreenKeyboard(
        self,
        initialText: AnyStr,
        fontSize: Optional[int] = ...,
        password: Optional[bool] = ...,
    ) -> AnyStr: ...
    def transform(self, *args: PyObject, **kwargs: AnyStr) -> PyObject: ...
    def warningBox(self, message: AnyStr, title: AnyStr = ...) -> None: ...
