from .thumbnail import Thumbnail
from .animation import Animation
from .audio import Audio
from .document import Document
from .photo import Photo
from .video import Video
from .sticker import Sticker
from .game import Game
from .voice import Voice
from .video_note import VideoNote
from .contact import Contact
from .location import Location
from .venue import Venue
from .webpage import WebPage
from .poll import Poll
from .dice import Dice
from .reaction import Reaction
