{
 "title": "Current Assets",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Total Assets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\"}<500_000_000) by (bucket, token)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\"}<500_000_000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Asset Summary",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\"}<500_000_000) by (token, bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Asset Breakdown",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(treasury_assets{param=\"usd value\"}<500_000_000) by (token, bucket)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}