# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/internal_redirect/allow_listed_routes/v3/allow_listed_routes_config.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("AllowListedRoutesConfig",)

from dataclasses import dataclass

import betterproto2

from ......message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class AllowListedRoutesConfig(betterproto2.Message):
    """
    [#protodoc-title: Allow listed routes internal redirect predicate]

    An internal redirect predicate that accepts only explicitly allowed target routes.
    [#extension: envoy.internal_redirect_predicates.allow_listed_routes]
    """

    allowed_route_names: "list[str]" = betterproto2.field(
        1, betterproto2.TYPE_STRING, repeated=True
    )
    """
    The list of routes that's allowed as redirect target by this predicate,
    identified by the route's :ref:`name <envoy_v3_api_field_config.route.v3.Route.route>`.
    Empty route names are not allowed.
    """


default_message_pool.register_message(
    "envoy.extensions.internal_redirect.allow_listed_routes.v3",
    "AllowListedRoutesConfig",
    AllowListedRoutesConfig,
)
