"""Prompt package for the dynamic Magentic workflow."""

from .manager import MANAGER_PROMPT
from .modules import EXECUTOR_PROMPT, GENERATOR_PROMPT, PLANNER_PROMPT, VERIFIER_PROMPT
from .tools import (
    BASE_GENERATOR_PROMPT,
    GOOGLE_SEARCH_PROMPT,
    PYTHON_CODER_PROMPT,
    WIKIPEDIA_SEARCH_PROMPT,
)

__all__ = [
    "BASE_GENERATOR_PROMPT",
    "EXECUTOR_PROMPT",
    "GENERATOR_PROMPT",
    "GOOGLE_SEARCH_PROMPT",
    "MANAGER_PROMPT",
    "PLANNER_PROMPT",
    "PYTHON_CODER_PROMPT",
    "VERIFIER_PROMPT",
    "WIKIPEDIA_SEARCH_PROMPT",
]
