# generated by fastapi-codegen:
#   filename:  /Users/ivasylen/Code/contracts/guardicore/connector
#   timestamp: 2025-10-23T14:22:01+00:00

from __future__ import annotations

from enum import Enum

from centra_sdk.utils.gc_serializer import GcSerializer


class Connector(Enum):
    CLOUD_AZURE = 'cloud_azure'
    CLOUD_AWS = 'cloud_aws'
    CLOUD_GCP = 'cloud_gcp'
    PACKETFENCE = 'packetfence'
    ALGOSEC = 'algosec'
    PENSANDO = 'pensando'
    PLATFORM = 'platform'
