# Generated by Django 3.2.4 on 2024-01-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allure_uploader_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
