from zfit._interfaces import ZfitSpace as ZfitSpace

def unbinned_to_hist_eager_edgesweightsargs(values, *edges_weights): ...
def unbinned_to_hist_eager(values, edges, weights=None): ...
def unbinned_to_binned(data, space, binned_class=None, initkwargs=None): ...
def unbinned_to_binindex(data, space, flow: bool = False): ...
