from _typeshed import Incomplete

def register_tensor_conversion(convertable, name=None, overload_operators: bool = True, priority: int = 10): ...

class OverloadableMixin: ...
class OverloadableMixinValues: ...
class MetaBaseParameter(Incomplete, Incomplete): ...
