import tensorflow_probability as tfp
from _typeshed import Incomplete
from collections.abc import Mapping
from zfit._interfaces import ZfitData as ZfitData, ZfitParameter as ZfitParameter, ZfitSpace as ZfitSpace
from zfit.util.container import convert_to_container as convert_to_container

class ValueHolder(tfp.experimental.AutoCompositeTensor):
    target: Incomplete
    norm: Incomplete
    holders: Incomplete
    variables: Incomplete
    args: Incomplete
    def __init__(self, args, variables: Mapping, norm: ValueHolder = None, target=None, holders=None) -> None: ...
    def get_var(self, name): ...
    def __getitem__(self, item): ...
    def __contains__(self, item) -> bool: ...
    @property
    def params(self): ...
    @property
    def space(self): ...
    @property
    def datasets(self): ...
