# `fsspec-utils` API Reference

Welcome to the `fsspec-utils` API reference documentation. This section provides detailed information on the various modules, classes, and functions available in the library.

## Core Modules

*   [`fsspec_utils.core.base`](fsspec_utils.core.base.qmd)

*   [`fsspec_utils.core.ext`](fsspec_utils.core.ext.qmd)

## Storage Options

*   [`fsspec_utils.storage_options.base`](fsspec_utils.storage_options.base.qmd)

*   [`fsspec_utils.storage_options.cloud`](fsspec_utils.storage_options.cloud.qmd)

*   [`fsspec_utils.storage_options.core`](fsspec_utils.storage_options.core.qmd)

*   [`fsspec_utils.storage_options.git`](fsspec_utils.storage_options.git.qmd)

## Utilities

*   [`fsspec_utils.utils.datetime`](fsspec_utils.utils.datetime.qmd)

*   [`fsspec_utils.utils.logging`](fsspec_utils.utils.logging.qmd)

*   [`fsspec_utils.utils.misc`](fsspec_utils.utils.misc.qmd)

*   [`fsspec_utils.utils.polars`](fsspec_utils.utils.polars.qmd)

*   [`fsspec_utils.utils.pyarrow`](fsspec_utils.utils.pyarrow.qmd)

*   [`fsspec_utils.utils.sql`](fsspec_utils.utils.sql.qmd)

*   [`fsspec_utils.utils.types`](fsspec_utils.utils.types.qmd)