# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum_notification_platform.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='enum_notification_platform.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\021ONE.Models.CSharp'),
  serialized_pb=_b('\n enum_notification_platform.proto*|\n\x18\x45numNotificationPlatform\x12!\n\x1dNOTIFICATION_PLATFORM_UNKNOWN\x10\x00\x12\x1e\n\x1aNOTIFICATION_PLATFORM_APNS\x10\x01\x12\x1d\n\x19NOTIFICATION_PLATFORM_FCM\x10\x02\x42\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')
)

_ENUMNOTIFICATIONPLATFORM = _descriptor.EnumDescriptor(
  name='EnumNotificationPlatform',
  full_name='EnumNotificationPlatform',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOTIFICATION_PLATFORM_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOTIFICATION_PLATFORM_APNS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOTIFICATION_PLATFORM_FCM', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=36,
  serialized_end=160,
)
_sym_db.RegisterEnumDescriptor(_ENUMNOTIFICATIONPLATFORM)

EnumNotificationPlatform = enum_type_wrapper.EnumTypeWrapper(_ENUMNOTIFICATIONPLATFORM)
NOTIFICATION_PLATFORM_UNKNOWN = 0
NOTIFICATION_PLATFORM_APNS = 1
NOTIFICATION_PLATFORM_FCM = 2


DESCRIPTOR.enum_types_by_name['EnumNotificationPlatform'] = _ENUMNOTIFICATIONPLATFORM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
