# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum_entity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='enum_entity.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\021ONE.Models.CSharp'),
  serialized_pb=_b('\n\x11\x65num_entity.proto*\x93\x01\n\nEnumEntity\x12\x12\n\x0e\x45NTITY_UNKNOWN\x10\x00\x12\x17\n\x13\x45NTITY_FORMTEMPLATE\x10\x01\x12\x16\n\x12\x45NTITY_APPLICATION\x10\x02\x12\x14\n\x10\x45NTITY_DASHBOARD\x10\x03\x12\x10\n\x0c\x45NTITY_GRAPH\x10\x04\x12\x18\n\x14\x45NTITY_WORKSHEETVIEW\x10\x05\x42\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')
)

_ENUMENTITY = _descriptor.EnumDescriptor(
  name='EnumEntity',
  full_name='EnumEntity',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ENTITY_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTITY_FORMTEMPLATE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTITY_APPLICATION', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTITY_DASHBOARD', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTITY_GRAPH', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTITY_WORKSHEETVIEW', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=22,
  serialized_end=169,
)
_sym_db.RegisterEnumDescriptor(_ENUMENTITY)

EnumEntity = enum_type_wrapper.EnumTypeWrapper(_ENUMENTITY)
ENTITY_UNKNOWN = 0
ENTITY_FORMTEMPLATE = 1
ENTITY_APPLICATION = 2
ENTITY_DASHBOARD = 3
ENTITY_GRAPH = 4
ENTITY_WORKSHEETVIEW = 5


DESCRIPTOR.enum_types_by_name['EnumEntity'] = _ENUMENTITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
