# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum_rendering_engine.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='enum_rendering_engine.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\021ONE.Models.CSharp'),
  serialized_pb=_b('\n\x1b\x65num_rendering_engine.proto*l\n\x13\x45numRenderingEngine\x12\x1c\n\x18RENDERING_ENGINE_UNKNOWN\x10\x00\x12\x1a\n\x16RENDERING_ENGINE_EXCEL\x10\x01\x12\x1b\n\x17RENDERING_ENGINE_CUSTOM\x10\x02\x42\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')
)

_ENUMRENDERINGENGINE = _descriptor.EnumDescriptor(
  name='EnumRenderingEngine',
  full_name='EnumRenderingEngine',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RENDERING_ENGINE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RENDERING_ENGINE_EXCEL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RENDERING_ENGINE_CUSTOM', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=31,
  serialized_end=139,
)
_sym_db.RegisterEnumDescriptor(_ENUMRENDERINGENGINE)

EnumRenderingEngine = enum_type_wrapper.EnumTypeWrapper(_ENUMRENDERINGENGINE)
RENDERING_ENGINE_UNKNOWN = 0
RENDERING_ENGINE_EXCEL = 1
RENDERING_ENGINE_CUSTOM = 2


DESCRIPTOR.enum_types_by_name['EnumRenderingEngine'] = _ENUMRENDERINGENGINE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
