# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: execution_details.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enum_time_unit_pb2 as enum__time__unit__pb2
import enum_output_placement_pb2 as enum__output__placement__pb2
import enum_wims_week_definition_pb2 as enum__wims__week__definition__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='execution_details.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\021ONE.Models.CSharp'),
  serialized_pb=_b('\n\x17\x65xecution_details.proto\x1a\x14\x65num_time_unit.proto\x1a\x1b\x65num_output_placement.proto\x1a\x1f\x65num_wims_week_definition.proto\"\xcf\x01\n\x10\x45xecutionDetails\x12-\n\x0foutputPlacement\x18\x01 \x01(\x0e\x32\x14.EnumOutputPlacement\x12\x1a\n\x12numberOfExecutions\x18\x02 \x01(\r\x12!\n\ntimePeriod\x18\x03 \x01(\x0e\x32\r.EnumTimeUnit\x12\x18\n\x10timeWindowOffset\x18\x04 \x01(\r\x12\x33\n\x12wimsWeekDefinition\x18\x05 \x01(\x0e\x32\x17.EnumWimsWeekDefinitionB\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')
  ,
  dependencies=[enum__time__unit__pb2.DESCRIPTOR,enum__output__placement__pb2.DESCRIPTOR,enum__wims__week__definition__pb2.DESCRIPTOR,])




_EXECUTIONDETAILS = _descriptor.Descriptor(
  name='ExecutionDetails',
  full_name='ExecutionDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='outputPlacement', full_name='ExecutionDetails.outputPlacement', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numberOfExecutions', full_name='ExecutionDetails.numberOfExecutions', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timePeriod', full_name='ExecutionDetails.timePeriod', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeWindowOffset', full_name='ExecutionDetails.timeWindowOffset', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wimsWeekDefinition', full_name='ExecutionDetails.wimsWeekDefinition', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=319,
)

_EXECUTIONDETAILS.fields_by_name['outputPlacement'].enum_type = enum__output__placement__pb2._ENUMOUTPUTPLACEMENT
_EXECUTIONDETAILS.fields_by_name['timePeriod'].enum_type = enum__time__unit__pb2._ENUMTIMEUNIT
_EXECUTIONDETAILS.fields_by_name['wimsWeekDefinition'].enum_type = enum__wims__week__definition__pb2._ENUMWIMSWEEKDEFINITION
DESCRIPTOR.message_types_by_name['ExecutionDetails'] = _EXECUTIONDETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExecutionDetails = _reflection.GeneratedProtocolMessageType('ExecutionDetails', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTIONDETAILS,
  '__module__' : 'execution_details_pb2'
  # @@protoc_insertion_point(class_scope:ExecutionDetails)
  })
_sym_db.RegisterMessage(ExecutionDetails)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
