# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/grpc_service/channel_credentials/xds/v3/xds_credentials.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("XdsCredentials",)

from dataclasses import dataclass

import betterproto2

from .......message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class XdsCredentials(betterproto2.Message):
    """
    [#protodoc-title: gRPC xDS Credentials]

    [#not-implemented-hide:]
    """

    fallback_credentials: "______google__protobuf__.Any | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    Fallback credentials. Required.
    """


default_message_pool.register_message(
    "envoy.extensions.grpc_service.channel_credentials.xds.v3",
    "XdsCredentials",
    XdsCredentials,
)


from .......google import protobuf as ______google__protobuf__
