// Copyright Contributors to the OpenVDB Project
// SPDX-License-Identifier: Apache-2.0
//
#ifndef FVDB_DETAIL_OPS_CONVOLUTION_BACKEND_CONVPRAGMAMESSAGE_H
#define FVDB_DETAIL_OPS_CONVOLUTION_BACKEND_CONVPRAGMAMESSAGE_H

#ifdef ENABLE_CONV_PRAGMA_MESSAGE
#define PRAGMA_MESSAGE(x) _Pragma(#x)
#else
#define PRAGMA_MESSAGE(x)
#endif

#endif // FVDB_DETAIL_OPS_CONVOLUTION_BACKEND_CONVPRAGMAMESSAGE_H
