class PDFCompatibilityError(Exception): ...
class LogicalUndefinedOperationError(Exception): ...
class OperationNotAllowedError(Exception): ...
class ExtendedPDFError(Exception): ...
class AlreadyExtendedPDFError(ExtendedPDFError): ...
class NotExtendedPDFError(ExtendedPDFError): ...
class ConversionError(Exception): ...
class SubclassingError(Exception): ...
class BasePDFSubclassingError(SubclassingError): ...
class MinimizerSubclassingError(SubclassingError): ...
class IntentionAmbiguousError(Exception): ...
class UnderdefinedError(IntentionAmbiguousError): ...
class LimitsUnderdefinedError(UnderdefinedError): ...
class NormRangeUnderdefinedError(UnderdefinedError): ...
class OverdefinedError(IntentionAmbiguousError): ...
class LimitsOverdefinedError(OverdefinedError): ...
class CoordinatesUnderdefinedError(UnderdefinedError): ...
class AxesAmbiguousError(IntentionAmbiguousError): ...
class NotSpecifiedError(Exception): ...
class LimitsNotSpecifiedError(NotSpecifiedError): ...
class NormRangeNotSpecifiedError(NotSpecifiedError): ...
class AxesNotSpecifiedError(NotSpecifiedError): ...
class ObsNotSpecifiedError(NotSpecifiedError): ...
class ParamNameNotUniqueError(Exception): ...
class IncompatibleError(Exception): ...
class ShapeIncompatibleError(IncompatibleError): ...
class CoordinatesIncompatibleError(IncompatibleError): ...
class ObsIncompatibleError(CoordinatesIncompatibleError): ...
class AxesIncompatibleError(CoordinatesIncompatibleError): ...
class SpaceIncompatibleError(IncompatibleError): ...
class LimitsIncompatibleError(IncompatibleError): ...
class NumberOfEventsIncompatibleError(ShapeIncompatibleError): ...
class InvalidLimitSubspaceError(Exception): ...
class ModelIncompatibleError(IncompatibleError): ...
class WeightsNotImplementedError(Exception): ...
class DataIsBatchedError(Exception): ...
class ParameterNotIndependentError(Exception): ...
class NotMinimizedError(Exception): ...
class IllegalInGraphModeError(Exception): ...
class CannotConvertToNumpyError(Exception): ...

class ZfitNotImplementedError(NotImplementedError):
    def __init__(self, *args: object) -> None: ...

class FunctionNotImplemented(ZfitNotImplementedError): ...
class StandardControlFlow(Exception): ...
class SpecificFunctionNotImplemented(FunctionNotImplemented): ...
class MinimizeNotImplemented(FunctionNotImplemented): ...
class MinimizeStepNotImplemented(FunctionNotImplemented): ...
class AnalyticNotImplemented(ZfitNotImplementedError): ...
class AnalyticIntegralNotImplemented(AnalyticNotImplemented): ...
class AnalyticSamplingNotImplemented(AnalyticNotImplemented): ...
class NormNotImplemented(StandardControlFlow): ...
NormRangeNotImplemented = NormNotImplemented

class MultipleLimitsNotImplemented(StandardControlFlow): ...
class InitNotImplemented(StandardControlFlow): ...
class VectorizedLimitsNotImplemented(StandardControlFlow): ...
class DerivativeCalculationError(ValueError): ...
class WorkInProgressError(Exception): ...

class BreakingAPIChangeError(Exception):
    def __init__(self, msg, *args: object) -> None: ...

class BehaviorUnderDiscussion(Exception):
    def __init__(self, msg, *args: object) -> None: ...

class MaximumIterationReached(StandardControlFlow): ...
class AnalyticGradientNotAvailable(Exception): ...
