from _typeshed import Incomplete

class ExperimentalFeatureWarning(UserWarning): ...

def warn_experimental_feature(func): ...

class AdvancedFeatureWarning(UserWarning): ...

warned_advanced: Incomplete

def warn_advanced_feature(message, identifier) -> None: ...

class ChangedFeatureWarning(UserWarning): ...

warned_changed: Incomplete

def warn_changed_feature(message, identifier) -> None: ...

warned_changing: Incomplete

def warn_changing_feature(message, identifier) -> None: ...

warned_once: Incomplete

def warn_once(message, identifier) -> None: ...
