"""CDN resources and headers for Tailwind CSS"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/resources.ipynb.

# %% auto 0
__all__ = ['TAILWIND_CDN', 'get_tailwind_headers']

# %% ../../nbs/core/resources.ipynb 3
from fasthtml.common import Link, Script, Style
from typing import List, Optional, Union, Literal
from pathlib import Path

# %% ../../nbs/core/resources.ipynb 5
# Core Tailwind CSS CDN resources
TAILWIND_CDN = "https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"

# %% ../../nbs/core/resources.ipynb 6
def get_tailwind_headers(
) -> List[Union[Link, Script]]:  # List of Link and Script elements for Tailwind CSS
    """Get the standard Tailwind CSS CDN headers."""
    headers = [
        Script(src=TAILWIND_CDN)
    ]
    return headers
