from typing import Any, overload

class Actuation:
    def PrintPropertyInfo(self, os: Any, classNameDotPropertyName: str, printFlagInfo: bool) -> bool: ...
    @overload
    def PrintPropertyInfo(self, os: Any, className: str, propertyName: str, printFlagInfo: bool) -> bool: ...
    def RegisterType(self, *args, **kwargs) -> Any: ...
    def RenameType(self, *args, **kwargs) -> Any: ...
    def SafeCopy(self, aObject: Object) -> Any: ...
    def __init__(self, aModel: Model) -> None: ...
    @overload
    def __init__(self, aFileName: str) -> None: ...
    @overload
    def __init__(self, aObject: Actuation) -> None: ...
    def assign(self, *args, **kwargs) -> Any: ...
    def begin(self, s: State) -> int: ...
    def clone(self) -> Any: ...
    def dump(self) -> str: ...
    def end(self, s: State) -> int: ...
    def getAuthors(self) -> str: ...
    def getClassName(self) -> str: ...
    def getColumnLabels(self) -> Any: ...
    def getConcreteClassName(self) -> str: ...
    def getDebugLevel(self) -> int: ...
    def getDefaultInstanceOfType(self, concreteClassName: str) -> Any: ...
    def getDescription(self) -> str: ...
    def getDocumentFileName(self) -> str: ...
    def getDocumentFileVersion(self) -> int: ...
    def getEndTime(self) -> float: ...
    def getForceStorage(self) -> Any: ...
    def getInDegrees(self) -> bool: ...
    def getInlined(self) -> bool: ...
    def getName(self) -> str: ...
    def getNumProperties(self) -> int: ...
    def getOn(self) -> bool: ...
    def getPowerStorage(self) -> Any: ...
    def getPrintResultFiles(self) -> bool: ...
    def getPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def getPropertyByName(self, name: str) -> Any: ...
    def getReferences(self) -> str: ...
    def getRegisteredTypenames(self, *args, **kwargs) -> Any: ...
    def getSerializeAllDefaults(self) -> bool: ...
    def getSpeedStorage(self) -> Any: ...
    def getStartTime(self) -> float: ...
    def getStepInterval(self) -> int: ...
    def getStorageList(self) -> Any: ...
    def hasProperty(self, name: str) -> bool: ...
    def isA(self, type: str) -> bool: ...
    def isEqualTo(self, aObject: Object) -> bool: ...
    def isKindOf(self, type: str) -> bool: ...
    def isObjectUpToDateWithProperties(self) -> bool: ...
    def makeObjectFromFile(self, fileName: str) -> Any: ...
    def newInstanceOfType(self, concreteClassName: str) -> Any: ...
    def printResults(self, aBaseName: str, aDir: str, aDT: float, aExtension: str) -> int: ...
    def printToXML(self, fileName: str) -> bool: ...
    def proceed(self, aStep: int) -> bool: ...
    def readObjectFromXMLNodeOrFile(self, *args, **kwargs) -> Any: ...
    def registerType(self, *args, **kwargs) -> Any: ...
    def renameType(self, *args, **kwargs) -> Any: ...
    def safeDownCast(self, obj: Object) -> Any: ...
    def setAllPropertiesUseDefault(self, *args, **kwargs) -> Any: ...
    def setAuthors(self, *args, **kwargs) -> Any: ...
    def setColumnLabels(self, *args, **kwargs) -> Any: ...
    def setDebugLevel(self, *args, **kwargs) -> Any: ...
    def setDescription(self, *args, **kwargs) -> Any: ...
    def setEndTime(self, *args, **kwargs) -> Any: ...
    def setInDegrees(self, *args, **kwargs) -> Any: ...
    def setInlined(self, *args, **kwargs) -> Any: ...
    def setModel(self, *args, **kwargs) -> Any: ...
    def setName(self, *args, **kwargs) -> Any: ...
    def setOn(self, *args, **kwargs) -> Any: ...
    def setPrintResultFiles(self, *args, **kwargs) -> Any: ...
    def setReferences(self, *args, **kwargs) -> Any: ...
    def setSerializeAllDefaults(self, *args, **kwargs) -> Any: ...
    def setStartTime(self, *args, **kwargs) -> Any: ...
    def setStatesStore(self, *args, **kwargs) -> Any: ...
    def setStepInterval(self, *args, **kwargs) -> Any: ...
    def setStorageCapacityIncrements(self, *args, **kwargs) -> Any: ...
    def step(self, s: State, setNumber: int) -> int: ...
    thisown: Any
    def toString(self) -> str: ...
    def updPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def updPropertyByName(self, name: str) -> Any: ...
    def updateFromXMLNode(self, *args, **kwargs) -> Any: ...
    def updateXMLNode(self, *args, **kwargs) -> Any: ...

class BodyKinematics:
    def PrintPropertyInfo(self, os: Any, classNameDotPropertyName: str, printFlagInfo: bool) -> bool: ...
    @overload
    def PrintPropertyInfo(self, os: Any, className: str, propertyName: str, printFlagInfo: bool) -> bool: ...
    def RegisterType(self, *args, **kwargs) -> Any: ...
    def RenameType(self, *args, **kwargs) -> Any: ...
    def SafeCopy(self, aObject: Object) -> Any: ...
    def __init__(self, aModel: Model, aInDegrees: bool) -> None: ...
    @overload
    def __init__(self, aFileName: str) -> None: ...
    @overload
    def __init__(self, aObject: BodyKinematics) -> None: ...
    def assign(self, *args, **kwargs) -> Any: ...
    def begin(self, s: State) -> int: ...
    def clone(self) -> Any: ...
    def dump(self) -> str: ...
    def end(self, s: State) -> int: ...
    def getAccelerationStorage(self) -> Any: ...
    def getAuthors(self) -> str: ...
    def getClassName(self) -> str: ...
    def getColumnLabels(self) -> Any: ...
    def getConcreteClassName(self) -> str: ...
    def getDebugLevel(self) -> int: ...
    def getDefaultInstanceOfType(self, concreteClassName: str) -> Any: ...
    def getDescription(self) -> str: ...
    def getDocumentFileName(self) -> str: ...
    def getDocumentFileVersion(self) -> int: ...
    def getEndTime(self) -> float: ...
    def getExpressResultsInLocalFrame(self) -> bool: ...
    def getInDegrees(self) -> bool: ...
    def getInlined(self) -> bool: ...
    def getName(self) -> str: ...
    def getNumProperties(self) -> int: ...
    def getOn(self) -> bool: ...
    def getPositionStorage(self) -> Any: ...
    def getPrintResultFiles(self) -> bool: ...
    def getPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def getPropertyByName(self, name: str) -> Any: ...
    def getReferences(self) -> str: ...
    def getRegisteredTypenames(self, *args, **kwargs) -> Any: ...
    def getSerializeAllDefaults(self) -> bool: ...
    def getStartTime(self) -> float: ...
    def getStepInterval(self) -> int: ...
    def getStorageList(self) -> Any: ...
    def getVelocityStorage(self) -> Any: ...
    def hasProperty(self, name: str) -> bool: ...
    def isA(self, type: str) -> bool: ...
    def isEqualTo(self, aObject: Object) -> bool: ...
    def isKindOf(self, type: str) -> bool: ...
    def isObjectUpToDateWithProperties(self) -> bool: ...
    def makeObjectFromFile(self, fileName: str) -> Any: ...
    def newInstanceOfType(self, concreteClassName: str) -> Any: ...
    def printResults(self, aBaseName: str, aDir: str, aDT: float, aExtension: str) -> int: ...
    def printToXML(self, fileName: str) -> bool: ...
    def proceed(self, aStep: int) -> bool: ...
    def readObjectFromXMLNodeOrFile(self, *args, **kwargs) -> Any: ...
    def registerType(self, *args, **kwargs) -> Any: ...
    def renameType(self, *args, **kwargs) -> Any: ...
    def safeDownCast(self, obj: Object) -> Any: ...
    def setAllPropertiesUseDefault(self, *args, **kwargs) -> Any: ...
    def setAuthors(self, *args, **kwargs) -> Any: ...
    def setBodiesToRecord(self, *args, **kwargs) -> Any: ...
    def setColumnLabels(self, *args, **kwargs) -> Any: ...
    def setDebugLevel(self, *args, **kwargs) -> Any: ...
    def setDescription(self, *args, **kwargs) -> Any: ...
    def setEndTime(self, *args, **kwargs) -> Any: ...
    def setExpressResultsInLocalFrame(self, *args, **kwargs) -> Any: ...
    def setInDegrees(self, *args, **kwargs) -> Any: ...
    def setInlined(self, *args, **kwargs) -> Any: ...
    def setModel(self, *args, **kwargs) -> Any: ...
    def setName(self, *args, **kwargs) -> Any: ...
    def setOn(self, *args, **kwargs) -> Any: ...
    def setPrintResultFiles(self, *args, **kwargs) -> Any: ...
    def setRecordCenterOfMass(self, *args, **kwargs) -> Any: ...
    def setReferences(self, *args, **kwargs) -> Any: ...
    def setSerializeAllDefaults(self, *args, **kwargs) -> Any: ...
    def setStartTime(self, *args, **kwargs) -> Any: ...
    def setStatesStore(self, *args, **kwargs) -> Any: ...
    def setStepInterval(self, *args, **kwargs) -> Any: ...
    def setStorageCapacityIncrements(self, *args, **kwargs) -> Any: ...
    def step(self, s: State, setNumber: int) -> int: ...
    thisown: Any
    def toString(self) -> str: ...
    def updPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def updPropertyByName(self, name: str) -> Any: ...
    def updateFromXMLNode(self, *args, **kwargs) -> Any: ...
    def updateXMLNode(self, *args, **kwargs) -> Any: ...

class ForceReporter:
    def PrintPropertyInfo(self, os: Any, classNameDotPropertyName: str, printFlagInfo: bool) -> bool: ...
    @overload
    def PrintPropertyInfo(self, os: Any, className: str, propertyName: str, printFlagInfo: bool) -> bool: ...
    def RegisterType(self, *args, **kwargs) -> Any: ...
    def RenameType(self, *args, **kwargs) -> Any: ...
    def SafeCopy(self, aObject: Object) -> Any: ...
    def __init__(self, aModel: Model) -> None: ...
    @overload
    def __init__(self, aFileName: str) -> None: ...
    @overload
    def __init__(self, aObject: ForceReporter) -> None: ...
    def assign(self, *args, **kwargs) -> Any: ...
    def begin(self, s: State) -> int: ...
    def clone(self) -> Any: ...
    def dump(self) -> str: ...
    def end(self, s: State) -> int: ...
    def getAuthors(self) -> str: ...
    def getClassName(self) -> str: ...
    def getColumnLabels(self) -> Any: ...
    def getConcreteClassName(self) -> str: ...
    def getDebugLevel(self) -> int: ...
    def getDefaultInstanceOfType(self, concreteClassName: str) -> Any: ...
    def getDescription(self) -> str: ...
    def getDocumentFileName(self) -> str: ...
    def getDocumentFileVersion(self) -> int: ...
    def getEndTime(self) -> float: ...
    def getForceStorage(self) -> Any: ...
    def getForcesTable(self) -> Any: ...
    def getInDegrees(self) -> bool: ...
    def getInlined(self) -> bool: ...
    def getName(self) -> str: ...
    def getNumProperties(self) -> int: ...
    def getOn(self) -> bool: ...
    def getPrintResultFiles(self) -> bool: ...
    def getPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def getPropertyByName(self, name: str) -> Any: ...
    def getReferences(self) -> str: ...
    def getRegisteredTypenames(self, *args, **kwargs) -> Any: ...
    def getSerializeAllDefaults(self) -> bool: ...
    def getStartTime(self) -> float: ...
    def getStepInterval(self) -> int: ...
    def getStorageList(self) -> Any: ...
    def hasProperty(self, name: str) -> bool: ...
    def includeConstraintForces(self, *args, **kwargs) -> Any: ...
    def isA(self, type: str) -> bool: ...
    def isEqualTo(self, aObject: Object) -> bool: ...
    def isKindOf(self, type: str) -> bool: ...
    def isObjectUpToDateWithProperties(self) -> bool: ...
    def makeObjectFromFile(self, fileName: str) -> Any: ...
    def newInstanceOfType(self, concreteClassName: str) -> Any: ...
    def printResults(self, aBaseName: str, aDir: str, aDT: float, aExtension: str) -> int: ...
    def printToXML(self, fileName: str) -> bool: ...
    def proceed(self, aStep: int) -> bool: ...
    def readObjectFromXMLNodeOrFile(self, *args, **kwargs) -> Any: ...
    def registerType(self, *args, **kwargs) -> Any: ...
    def renameType(self, *args, **kwargs) -> Any: ...
    def safeDownCast(self, obj: Object) -> Any: ...
    def setAllPropertiesUseDefault(self, *args, **kwargs) -> Any: ...
    def setAuthors(self, *args, **kwargs) -> Any: ...
    def setColumnLabels(self, *args, **kwargs) -> Any: ...
    def setDebugLevel(self, *args, **kwargs) -> Any: ...
    def setDescription(self, *args, **kwargs) -> Any: ...
    def setEndTime(self, *args, **kwargs) -> Any: ...
    def setInDegrees(self, *args, **kwargs) -> Any: ...
    def setInlined(self, *args, **kwargs) -> Any: ...
    def setModel(self, *args, **kwargs) -> Any: ...
    def setName(self, *args, **kwargs) -> Any: ...
    def setOn(self, *args, **kwargs) -> Any: ...
    def setPrintResultFiles(self, *args, **kwargs) -> Any: ...
    def setReferences(self, *args, **kwargs) -> Any: ...
    def setSerializeAllDefaults(self, *args, **kwargs) -> Any: ...
    def setStartTime(self, *args, **kwargs) -> Any: ...
    def setStatesStore(self, *args, **kwargs) -> Any: ...
    def setStepInterval(self, *args, **kwargs) -> Any: ...
    def step(self, s: State, setNumber: int) -> int: ...
    thisown: Any
    def toString(self) -> str: ...
    def updForceStorage(self) -> Any: ...
    def updPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def updPropertyByName(self, name: str) -> Any: ...
    def updateFromXMLNode(self, *args, **kwargs) -> Any: ...
    def updateXMLNode(self, *args, **kwargs) -> Any: ...

class IMUDataReporter:
    def PrintPropertyInfo(self, os: Any, classNameDotPropertyName: str, printFlagInfo: bool) -> bool: ...
    @overload
    def PrintPropertyInfo(self, os: Any, className: str, propertyName: str, printFlagInfo: bool) -> bool: ...
    def RegisterType(self, *args, **kwargs) -> Any: ...
    def RenameType(self, *args, **kwargs) -> Any: ...
    def SafeCopy(self, aObject: Object) -> Any: ...
    def __init__(self, aModel: Model) -> None: ...
    @overload
    def __init__(self, aObject: IMUDataReporter) -> None: ...
    def append_compute_accelerations_without_forces(self, value: Any) -> int: ...
    def append_frame_paths(self, value: str) -> int: ...
    def append_report_accelerometer_signals(self, value: Any) -> int: ...
    def append_report_gyroscope_signals(self, value: Any) -> int: ...
    def append_report_orientations(self, value: Any) -> int: ...
    def assign(self, *args, **kwargs) -> Any: ...
    def begin(self, s: State) -> int: ...
    def clone(self) -> Any: ...
    def constructProperty_compute_accelerations_without_forces(self, *args, **kwargs) -> Any: ...
    def constructProperty_frame_paths(self, *args, **kwargs) -> Any: ...
    def constructProperty_report_accelerometer_signals(self, *args, **kwargs) -> Any: ...
    def constructProperty_report_gyroscope_signals(self, *args, **kwargs) -> Any: ...
    def constructProperty_report_orientations(self, *args, **kwargs) -> Any: ...
    def copyProperty_compute_accelerations_without_forces(self, *args, **kwargs) -> Any: ...
    def copyProperty_frame_paths(self, *args, **kwargs) -> Any: ...
    def copyProperty_report_accelerometer_signals(self, *args, **kwargs) -> Any: ...
    def copyProperty_report_gyroscope_signals(self, *args, **kwargs) -> Any: ...
    def copyProperty_report_orientations(self, *args, **kwargs) -> Any: ...
    def dump(self) -> str: ...
    def end(self, s: State) -> int: ...
    def getAccelerometerSignalsTable(self) -> Any: ...
    def getAuthors(self) -> str: ...
    def getClassName(self) -> str: ...
    def getColumnLabels(self) -> Any: ...
    def getConcreteClassName(self) -> str: ...
    def getDebugLevel(self) -> int: ...
    def getDefaultInstanceOfType(self, concreteClassName: str) -> Any: ...
    def getDescription(self) -> str: ...
    def getDocumentFileName(self) -> str: ...
    def getDocumentFileVersion(self) -> int: ...
    def getEndTime(self) -> float: ...
    def getGyroscopeSignalsTable(self) -> Any: ...
    def getInDegrees(self) -> bool: ...
    def getInlined(self) -> bool: ...
    def getName(self) -> str: ...
    def getNumProperties(self) -> int: ...
    def getOn(self) -> bool: ...
    def getOrientationsTable(self) -> Any: ...
    def getPrintResultFiles(self) -> bool: ...
    def getPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def getPropertyByName(self, name: str) -> Any: ...
    def getReferences(self) -> str: ...
    def getRegisteredTypenames(self, *args, **kwargs) -> Any: ...
    def getSerializeAllDefaults(self) -> bool: ...
    def getStartTime(self) -> float: ...
    def getStepInterval(self) -> int: ...
    def getStorageList(self) -> Any: ...
    def get_compute_accelerations_without_forces(self, i: int) -> Any: ...
    @overload
    def get_compute_accelerations_without_forces(self) -> Any: ...
    def get_frame_paths(self, i: int) -> str: ...
    def get_report_accelerometer_signals(self, i: int) -> Any: ...
    @overload
    def get_report_accelerometer_signals(self) -> Any: ...
    def get_report_gyroscope_signals(self, i: int) -> Any: ...
    @overload
    def get_report_gyroscope_signals(self) -> Any: ...
    def get_report_orientations(self, i: int) -> Any: ...
    @overload
    def get_report_orientations(self) -> Any: ...
    def hasProperty(self, name: str) -> bool: ...
    def isA(self, type: str) -> bool: ...
    def isEqualTo(self, aObject: Object) -> bool: ...
    def isKindOf(self, type: str) -> bool: ...
    def isObjectUpToDateWithProperties(self) -> bool: ...
    def makeObjectFromFile(self, fileName: str) -> Any: ...
    def newInstanceOfType(self, concreteClassName: str) -> Any: ...
    def printResults(self, aBaseName: str, aDir: str, aDT: float, aExtension: str) -> int: ...
    def printToXML(self, fileName: str) -> bool: ...
    def proceed(self, aStep: int) -> bool: ...
    def readObjectFromXMLNodeOrFile(self, *args, **kwargs) -> Any: ...
    def registerType(self, *args, **kwargs) -> Any: ...
    def renameType(self, *args, **kwargs) -> Any: ...
    def safeDownCast(self, obj: Object) -> Any: ...
    def setAllPropertiesUseDefault(self, *args, **kwargs) -> Any: ...
    def setAuthors(self, *args, **kwargs) -> Any: ...
    def setColumnLabels(self, *args, **kwargs) -> Any: ...
    def setDebugLevel(self, *args, **kwargs) -> Any: ...
    def setDescription(self, *args, **kwargs) -> Any: ...
    def setEndTime(self, *args, **kwargs) -> Any: ...
    def setInDegrees(self, *args, **kwargs) -> Any: ...
    def setInlined(self, *args, **kwargs) -> Any: ...
    def setModel(self, *args, **kwargs) -> Any: ...
    def setName(self, *args, **kwargs) -> Any: ...
    def setNull(self, *args, **kwargs) -> Any: ...
    def setOn(self, *args, **kwargs) -> Any: ...
    def setPrintResultFiles(self, *args, **kwargs) -> Any: ...
    def setReferences(self, *args, **kwargs) -> Any: ...
    def setSerializeAllDefaults(self, *args, **kwargs) -> Any: ...
    def setStartTime(self, *args, **kwargs) -> Any: ...
    def setStatesStore(self, *args, **kwargs) -> Any: ...
    def setStepInterval(self, *args, **kwargs) -> Any: ...
    def set_compute_accelerations_without_forces(self, *args, **kwargs) -> Any: ...
    def set_frame_paths(self, *args, **kwargs) -> Any: ...
    def set_report_accelerometer_signals(self, *args, **kwargs) -> Any: ...
    def set_report_gyroscope_signals(self, *args, **kwargs) -> Any: ...
    def set_report_orientations(self, *args, **kwargs) -> Any: ...
    def step(self, s: State, setNumber: int) -> int: ...
    thisown: Any
    def toString(self) -> str: ...
    def updPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def updPropertyByName(self, name: str) -> Any: ...
    def upd_compute_accelerations_without_forces(self, i: int) -> bool: ...
    @overload
    def upd_compute_accelerations_without_forces(self) -> Any: ...
    def upd_frame_paths(self, i: int) -> Any: ...
    def upd_report_accelerometer_signals(self, i: int) -> bool: ...
    @overload
    def upd_report_accelerometer_signals(self) -> Any: ...
    def upd_report_gyroscope_signals(self, i: int) -> bool: ...
    @overload
    def upd_report_gyroscope_signals(self) -> Any: ...
    def upd_report_orientations(self, i: int) -> bool: ...
    @overload
    def upd_report_orientations(self) -> Any: ...
    def updateFromXMLNode(self, *args, **kwargs) -> Any: ...
    def updateXMLNode(self, *args, **kwargs) -> Any: ...

class InducedAccelerations:
    def PrintPropertyInfo(self, os: Any, classNameDotPropertyName: str, printFlagInfo: bool) -> bool: ...
    @overload
    def PrintPropertyInfo(self, os: Any, className: str, propertyName: str, printFlagInfo: bool) -> bool: ...
    def RegisterType(self, *args, **kwargs) -> Any: ...
    def RenameType(self, *args, **kwargs) -> Any: ...
    def SafeCopy(self, aObject: Object) -> Any: ...
    def __init__(self, aModel: Model) -> None: ...
    @overload
    def __init__(self, aFileName: str) -> None: ...
    @overload
    def __init__(self, aObject: InducedAccelerations) -> None: ...
    def addContactConstraintFromExternalForce(self, *args, **kwargs) -> Any: ...
    def applyContactConstraintAccordingToExternalForces(self, s: State) -> Any: ...
    def assign(self, *args, **kwargs) -> Any: ...
    def begin(self, s: State) -> int: ...
    def clone(self) -> Any: ...
    def dump(self) -> str: ...
    def end(self, s: State) -> int: ...
    def getAuthors(self) -> str: ...
    def getClassName(self) -> str: ...
    def getColumnLabels(self) -> Any: ...
    def getConcreteClassName(self) -> str: ...
    def getDebugLevel(self) -> int: ...
    def getDefaultInstanceOfType(self, concreteClassName: str) -> Any: ...
    def getDescription(self) -> str: ...
    def getDocumentFileName(self) -> str: ...
    def getDocumentFileVersion(self) -> int: ...
    def getEndTime(self) -> float: ...
    def getInDegrees(self) -> bool: ...
    def getInlined(self) -> bool: ...
    def getName(self) -> str: ...
    def getNumProperties(self) -> int: ...
    def getOn(self) -> bool: ...
    def getPrintResultFiles(self) -> bool: ...
    def getPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def getPropertyByName(self, name: str) -> Any: ...
    def getReferences(self) -> str: ...
    def getRegisteredTypenames(self, *args, **kwargs) -> Any: ...
    def getSerializeAllDefaults(self) -> bool: ...
    def getStartTime(self) -> float: ...
    def getStepInterval(self) -> int: ...
    def getStorageList(self) -> Any: ...
    def hasProperty(self, name: str) -> bool: ...
    def initialize(self, *args, **kwargs) -> Any: ...
    def isA(self, type: str) -> bool: ...
    def isEqualTo(self, aObject: Object) -> bool: ...
    def isKindOf(self, type: str) -> bool: ...
    def isObjectUpToDateWithProperties(self) -> bool: ...
    def makeObjectFromFile(self, fileName: str) -> Any: ...
    def newInstanceOfType(self, concreteClassName: str) -> Any: ...
    def printResults(self, aBaseName: str, aDir: str, aDT: float, aExtension: str) -> int: ...
    def printToXML(self, fileName: str) -> bool: ...
    def proceed(self, aStep: int) -> bool: ...
    def readObjectFromXMLNodeOrFile(self, *args, **kwargs) -> Any: ...
    def registerType(self, *args, **kwargs) -> Any: ...
    def renameType(self, *args, **kwargs) -> Any: ...
    def safeDownCast(self, obj: Object) -> Any: ...
    def setAllPropertiesUseDefault(self, *args, **kwargs) -> Any: ...
    def setAuthors(self, *args, **kwargs) -> Any: ...
    def setColumnLabels(self, *args, **kwargs) -> Any: ...
    def setDebugLevel(self, *args, **kwargs) -> Any: ...
    def setDescription(self, *args, **kwargs) -> Any: ...
    def setEndTime(self, *args, **kwargs) -> Any: ...
    def setInDegrees(self, *args, **kwargs) -> Any: ...
    def setInlined(self, *args, **kwargs) -> Any: ...
    def setModel(self, *args, **kwargs) -> Any: ...
    def setName(self, *args, **kwargs) -> Any: ...
    def setOn(self, *args, **kwargs) -> Any: ...
    def setPrintResultFiles(self, *args, **kwargs) -> Any: ...
    def setReferences(self, *args, **kwargs) -> Any: ...
    def setSerializeAllDefaults(self, *args, **kwargs) -> Any: ...
    def setStartTime(self, *args, **kwargs) -> Any: ...
    def setStatesStore(self, *args, **kwargs) -> Any: ...
    def setStepInterval(self, *args, **kwargs) -> Any: ...
    def step(self, s: State, stepNumber: int) -> int: ...
    thisown: Any
    def toString(self) -> str: ...
    def updPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def updPropertyByName(self, name: str) -> Any: ...
    def updateFromXMLNode(self, *args, **kwargs) -> Any: ...
    def updateXMLNode(self, *args, **kwargs) -> Any: ...

class InverseDynamics:
    def PrintPropertyInfo(self, os: Any, classNameDotPropertyName: str, printFlagInfo: bool) -> bool: ...
    @overload
    def PrintPropertyInfo(self, os: Any, className: str, propertyName: str, printFlagInfo: bool) -> bool: ...
    def RegisterType(self, *args, **kwargs) -> Any: ...
    def RenameType(self, *args, **kwargs) -> Any: ...
    def SafeCopy(self, aObject: Object) -> Any: ...
    def __init__(self, aModel: Model) -> None: ...
    @overload
    def __init__(self, aObject: InverseDynamics) -> None: ...
    def assign(self, *args, **kwargs) -> Any: ...
    def begin(self, s: State) -> int: ...
    def clone(self) -> Any: ...
    def dump(self) -> str: ...
    def end(self, s: State) -> int: ...
    def getAuthors(self) -> str: ...
    def getClassName(self) -> str: ...
    def getColumnLabels(self) -> Any: ...
    def getConcreteClassName(self) -> str: ...
    def getDebugLevel(self) -> int: ...
    def getDefaultInstanceOfType(self, concreteClassName: str) -> Any: ...
    def getDescription(self) -> str: ...
    def getDocumentFileName(self) -> str: ...
    def getDocumentFileVersion(self) -> int: ...
    def getEndTime(self) -> float: ...
    def getInDegrees(self) -> bool: ...
    def getInlined(self) -> bool: ...
    def getName(self) -> str: ...
    def getNumProperties(self) -> int: ...
    def getOn(self) -> bool: ...
    def getPrintResultFiles(self) -> bool: ...
    def getPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def getPropertyByName(self, name: str) -> Any: ...
    def getReferences(self) -> str: ...
    def getRegisteredTypenames(self, *args, **kwargs) -> Any: ...
    def getSerializeAllDefaults(self) -> bool: ...
    def getStartTime(self) -> float: ...
    def getStepInterval(self) -> int: ...
    def getStorage(self) -> Any: ...
    def getStorageList(self) -> Any: ...
    def getUseModelForceSet(self) -> bool: ...
    def hasProperty(self, name: str) -> bool: ...
    def isA(self, type: str) -> bool: ...
    def isEqualTo(self, aObject: Object) -> bool: ...
    def isKindOf(self, type: str) -> bool: ...
    def isObjectUpToDateWithProperties(self) -> bool: ...
    def makeObjectFromFile(self, fileName: str) -> Any: ...
    def newInstanceOfType(self, concreteClassName: str) -> Any: ...
    def printResults(self, aBaseName: str, aDir: str, aDT: float, aExtension: str) -> int: ...
    def printToXML(self, fileName: str) -> bool: ...
    def proceed(self, aStep: int) -> bool: ...
    def readObjectFromXMLNodeOrFile(self, *args, **kwargs) -> Any: ...
    def registerType(self, *args, **kwargs) -> Any: ...
    def renameType(self, *args, **kwargs) -> Any: ...
    def safeDownCast(self, obj: Object) -> Any: ...
    def setAllPropertiesUseDefault(self, *args, **kwargs) -> Any: ...
    def setAuthors(self, *args, **kwargs) -> Any: ...
    def setColumnLabels(self, *args, **kwargs) -> Any: ...
    def setDebugLevel(self, *args, **kwargs) -> Any: ...
    def setDescription(self, *args, **kwargs) -> Any: ...
    def setEndTime(self, *args, **kwargs) -> Any: ...
    def setInDegrees(self, *args, **kwargs) -> Any: ...
    def setInlined(self, *args, **kwargs) -> Any: ...
    def setModel(self, *args, **kwargs) -> Any: ...
    def setName(self, *args, **kwargs) -> Any: ...
    def setOn(self, *args, **kwargs) -> Any: ...
    def setPrintResultFiles(self, *args, **kwargs) -> Any: ...
    def setReferences(self, *args, **kwargs) -> Any: ...
    def setSerializeAllDefaults(self, *args, **kwargs) -> Any: ...
    def setStartTime(self, *args, **kwargs) -> Any: ...
    def setStatesStore(self, *args, **kwargs) -> Any: ...
    def setStepInterval(self, *args, **kwargs) -> Any: ...
    def setStorageCapacityIncrements(self, *args, **kwargs) -> Any: ...
    def setUseModelForceSet(self, *args, **kwargs) -> Any: ...
    def step(self, s: State, stepNumber: int) -> int: ...
    thisown: Any
    def toString(self) -> str: ...
    def updPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def updPropertyByName(self, name: str) -> Any: ...
    def updateFromXMLNode(self, *args, **kwargs) -> Any: ...
    def updateXMLNode(self, *args, **kwargs) -> Any: ...

class JointReaction:
    def PrintPropertyInfo(self, os: Any, classNameDotPropertyName: str, printFlagInfo: bool) -> bool: ...
    @overload
    def PrintPropertyInfo(self, os: Any, className: str, propertyName: str, printFlagInfo: bool) -> bool: ...
    def RegisterType(self, *args, **kwargs) -> Any: ...
    def RenameType(self, *args, **kwargs) -> Any: ...
    def SafeCopy(self, aObject: Object) -> Any: ...
    def __init__(self, aModel: Model) -> None: ...
    @overload
    def __init__(self, aFileName: str) -> None: ...
    @overload
    def __init__(self, aObject: JointReaction) -> None: ...
    def assign(self, *args, **kwargs) -> Any: ...
    def begin(self, s: State) -> int: ...
    def clone(self) -> Any: ...
    def dump(self) -> str: ...
    def end(self, s: State) -> int: ...
    def getAuthors(self) -> str: ...
    def getClassName(self) -> str: ...
    def getColumnLabels(self) -> Any: ...
    def getConcreteClassName(self) -> str: ...
    def getDebugLevel(self) -> int: ...
    def getDefaultInstanceOfType(self, concreteClassName: str) -> Any: ...
    def getDescription(self) -> str: ...
    def getDocumentFileName(self) -> str: ...
    def getDocumentFileVersion(self) -> int: ...
    def getEndTime(self) -> float: ...
    def getForcesFileName(self) -> str: ...
    def getInDegrees(self) -> bool: ...
    def getInFrame(self) -> Any: ...
    def getInlined(self) -> bool: ...
    def getJointNames(self) -> Any: ...
    def getName(self) -> str: ...
    def getNumProperties(self) -> int: ...
    def getOn(self) -> bool: ...
    def getOnBody(self) -> Any: ...
    def getPrintResultFiles(self) -> bool: ...
    def getPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def getPropertyByName(self, name: str) -> Any: ...
    def getReferences(self) -> str: ...
    def getRegisteredTypenames(self, *args, **kwargs) -> Any: ...
    def getSerializeAllDefaults(self) -> bool: ...
    def getStartTime(self) -> float: ...
    def getStepInterval(self) -> int: ...
    def getStorageList(self) -> Any: ...
    def hasProperty(self, name: str) -> bool: ...
    def isA(self, type: str) -> bool: ...
    def isEqualTo(self, aObject: Object) -> bool: ...
    def isKindOf(self, type: str) -> bool: ...
    def isObjectUpToDateWithProperties(self) -> bool: ...
    def makeObjectFromFile(self, fileName: str) -> Any: ...
    def newInstanceOfType(self, concreteClassName: str) -> Any: ...
    def printResults(self, aBaseName: str, aDir: str, aDT: float, aExtension: str) -> int: ...
    def printToXML(self, fileName: str) -> bool: ...
    def proceed(self, aStep: int) -> bool: ...
    def readObjectFromXMLNodeOrFile(self, *args, **kwargs) -> Any: ...
    def registerType(self, *args, **kwargs) -> Any: ...
    def renameType(self, *args, **kwargs) -> Any: ...
    def safeDownCast(self, obj: Object) -> Any: ...
    def setAllPropertiesUseDefault(self, *args, **kwargs) -> Any: ...
    def setAuthors(self, *args, **kwargs) -> Any: ...
    def setColumnLabels(self, *args, **kwargs) -> Any: ...
    def setDebugLevel(self, *args, **kwargs) -> Any: ...
    def setDescription(self, *args, **kwargs) -> Any: ...
    def setEndTime(self, *args, **kwargs) -> Any: ...
    def setForcesFileName(self, *args, **kwargs) -> Any: ...
    def setInDegrees(self, *args, **kwargs) -> Any: ...
    def setInFrame(self, *args, **kwargs) -> Any: ...
    def setInlined(self, *args, **kwargs) -> Any: ...
    def setJointNames(self, *args, **kwargs) -> Any: ...
    def setModel(self, *args, **kwargs) -> Any: ...
    def setName(self, *args, **kwargs) -> Any: ...
    def setOn(self, *args, **kwargs) -> Any: ...
    def setOnBody(self, *args, **kwargs) -> Any: ...
    def setPrintResultFiles(self, *args, **kwargs) -> Any: ...
    def setReferences(self, *args, **kwargs) -> Any: ...
    def setSerializeAllDefaults(self, *args, **kwargs) -> Any: ...
    def setStartTime(self, *args, **kwargs) -> Any: ...
    def setStatesStore(self, *args, **kwargs) -> Any: ...
    def setStepInterval(self, *args, **kwargs) -> Any: ...
    def step(self, s: State, setNumber: int) -> int: ...
    thisown: Any
    def toString(self) -> str: ...
    def updPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def updPropertyByName(self, name: str) -> Any: ...
    def updateFromXMLNode(self, *args, **kwargs) -> Any: ...
    def updateXMLNode(self, *args, **kwargs) -> Any: ...

class Kinematics:
    def PrintPropertyInfo(self, os: Any, classNameDotPropertyName: str, printFlagInfo: bool) -> bool: ...
    @overload
    def PrintPropertyInfo(self, os: Any, className: str, propertyName: str, printFlagInfo: bool) -> bool: ...
    def RegisterType(self, *args, **kwargs) -> Any: ...
    def RenameType(self, *args, **kwargs) -> Any: ...
    def SafeCopy(self, aObject: Object) -> Any: ...
    def __init__(self, aModel: Model) -> None: ...
    @overload
    def __init__(self, aFileName: str) -> None: ...
    def assign(self, *args, **kwargs) -> Any: ...
    def begin(self, s: State) -> int: ...
    def clone(self) -> Any: ...
    def dump(self) -> str: ...
    def end(self, s: State) -> int: ...
    def getAccelerationStorage(self) -> Any: ...
    def getAuthors(self) -> str: ...
    def getClassName(self) -> str: ...
    def getColumnLabels(self) -> Any: ...
    def getConcreteClassName(self) -> str: ...
    def getDebugLevel(self) -> int: ...
    def getDefaultInstanceOfType(self, concreteClassName: str) -> Any: ...
    def getDescription(self) -> str: ...
    def getDocumentFileName(self) -> str: ...
    def getDocumentFileVersion(self) -> int: ...
    def getEndTime(self) -> float: ...
    def getInDegrees(self) -> bool: ...
    def getInlined(self) -> bool: ...
    def getName(self) -> str: ...
    def getNumProperties(self) -> int: ...
    def getOn(self) -> bool: ...
    def getPositionStorage(self) -> Any: ...
    def getPrintResultFiles(self) -> bool: ...
    def getPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def getPropertyByName(self, name: str) -> Any: ...
    def getReferences(self) -> str: ...
    def getRegisteredTypenames(self, *args, **kwargs) -> Any: ...
    def getSerializeAllDefaults(self) -> bool: ...
    def getStartTime(self) -> float: ...
    def getStepInterval(self) -> int: ...
    def getStorageList(self) -> Any: ...
    def getVelocityStorage(self) -> Any: ...
    def hasProperty(self, name: str) -> bool: ...
    def isA(self, type: str) -> bool: ...
    def isEqualTo(self, aObject: Object) -> bool: ...
    def isKindOf(self, type: str) -> bool: ...
    def isObjectUpToDateWithProperties(self) -> bool: ...
    def makeObjectFromFile(self, fileName: str) -> Any: ...
    def newInstanceOfType(self, concreteClassName: str) -> Any: ...
    def printResults(self, aBaseName: str, aDir: str, aDT: float, aExtension: str) -> int: ...
    def printToXML(self, fileName: str) -> bool: ...
    def proceed(self, aStep: int) -> bool: ...
    def readObjectFromXMLNodeOrFile(self, *args, **kwargs) -> Any: ...
    def registerType(self, *args, **kwargs) -> Any: ...
    def renameType(self, *args, **kwargs) -> Any: ...
    def safeDownCast(self, obj: Object) -> Any: ...
    def setAllPropertiesUseDefault(self, *args, **kwargs) -> Any: ...
    def setAuthors(self, *args, **kwargs) -> Any: ...
    def setColumnLabels(self, *args, **kwargs) -> Any: ...
    def setDebugLevel(self, *args, **kwargs) -> Any: ...
    def setDescription(self, *args, **kwargs) -> Any: ...
    def setEndTime(self, *args, **kwargs) -> Any: ...
    def setInDegrees(self, *args, **kwargs) -> Any: ...
    def setInlined(self, *args, **kwargs) -> Any: ...
    def setModel(self, *args, **kwargs) -> Any: ...
    def setName(self, *args, **kwargs) -> Any: ...
    def setOn(self, *args, **kwargs) -> Any: ...
    def setPrintResultFiles(self, *args, **kwargs) -> Any: ...
    def setRecordAccelerations(self, *args, **kwargs) -> Any: ...
    def setReferences(self, *args, **kwargs) -> Any: ...
    def setSerializeAllDefaults(self, *args, **kwargs) -> Any: ...
    def setStartTime(self, *args, **kwargs) -> Any: ...
    def setStatesStore(self, *args, **kwargs) -> Any: ...
    def setStepInterval(self, *args, **kwargs) -> Any: ...
    def setStorageCapacityIncrements(self, *args, **kwargs) -> Any: ...
    def step(self, s: State, setNumber: int) -> int: ...
    thisown: Any
    def toString(self) -> str: ...
    def updPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def updPropertyByName(self, name: str) -> Any: ...
    def updateFromXMLNode(self, *args, **kwargs) -> Any: ...
    def updateXMLNode(self, *args, **kwargs) -> Any: ...

class MuscleAnalysis:
    def PrintPropertyInfo(self, os: Any, classNameDotPropertyName: str, printFlagInfo: bool) -> bool: ...
    @overload
    def PrintPropertyInfo(self, os: Any, className: str, propertyName: str, printFlagInfo: bool) -> bool: ...
    def RegisterType(self, *args, **kwargs) -> Any: ...
    def RenameType(self, *args, **kwargs) -> Any: ...
    def SafeCopy(self, aObject: Object) -> Any: ...
    def __init__(self, aModel: Model) -> None: ...
    @overload
    def __init__(self, aFileName: str) -> None: ...
    @overload
    def __init__(self, aObject: MuscleAnalysis) -> None: ...
    def allocateStorageObjects(self, *args, **kwargs) -> Any: ...
    def assign(self, *args, **kwargs) -> Any: ...
    def begin(self, s: State) -> int: ...
    def clone(self) -> Any: ...
    def dump(self) -> str: ...
    def end(self, s: State) -> int: ...
    def getActiveFiberForceAlongTendonStorage(self) -> Any: ...
    def getActiveFiberForceStorage(self) -> Any: ...
    def getAuthors(self) -> str: ...
    def getClassName(self) -> str: ...
    def getColumnLabels(self) -> Any: ...
    def getComputeMoments(self) -> bool: ...
    def getConcreteClassName(self) -> str: ...
    def getDebugLevel(self) -> int: ...
    def getDefaultInstanceOfType(self, concreteClassName: str) -> Any: ...
    def getDescription(self) -> str: ...
    def getDocumentFileName(self) -> str: ...
    def getDocumentFileVersion(self) -> int: ...
    def getEndTime(self) -> float: ...
    def getFiberActivePowerStorage(self) -> Any: ...
    def getFiberForceStorage(self) -> Any: ...
    def getFiberLengthStorage(self) -> Any: ...
    def getFiberPassivePowerStorage(self) -> Any: ...
    def getFiberVelocityStorage(self) -> Any: ...
    def getForceStorage(self) -> Any: ...
    def getInDegrees(self) -> bool: ...
    def getInlined(self) -> bool: ...
    def getMusclePowerStorage(self) -> Any: ...
    def getMuscleTendonLengthStorage(self) -> Any: ...
    def getName(self) -> str: ...
    def getNormalizedFiberLengthStorage(self) -> Any: ...
    def getNormalizedFiberVelocityStorage(self) -> Any: ...
    def getNumProperties(self) -> int: ...
    def getOn(self) -> bool: ...
    def getPassiveFiberForceAlongTendonStorage(self) -> Any: ...
    def getPassiveFiberForceStorage(self) -> Any: ...
    def getPennationAngleStorage(self) -> Any: ...
    def getPennationAngularVelocityStorage(self) -> Any: ...
    def getPrintResultFiles(self) -> bool: ...
    def getPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def getPropertyByName(self, name: str) -> Any: ...
    def getReferences(self) -> str: ...
    def getRegisteredTypenames(self, *args, **kwargs) -> Any: ...
    def getSerializeAllDefaults(self) -> bool: ...
    def getStartTime(self) -> float: ...
    def getStepInterval(self) -> int: ...
    def getStorageList(self) -> Any: ...
    def getTendonLengthStorage(self) -> Any: ...
    def getTendonPowerStorage(self) -> Any: ...
    def hasProperty(self, name: str) -> bool: ...
    def isA(self, type: str) -> bool: ...
    def isEqualTo(self, aObject: Object) -> bool: ...
    def isKindOf(self, type: str) -> bool: ...
    def isObjectUpToDateWithProperties(self) -> bool: ...
    def makeObjectFromFile(self, fileName: str) -> Any: ...
    def newInstanceOfType(self, concreteClassName: str) -> Any: ...
    def printResults(self, aBaseName: str, aDir: str, aDT: float, aExtension: str) -> int: ...
    def printToXML(self, fileName: str) -> bool: ...
    def proceed(self, aStep: int) -> bool: ...
    def readObjectFromXMLNodeOrFile(self, *args, **kwargs) -> Any: ...
    def registerType(self, *args, **kwargs) -> Any: ...
    def renameType(self, *args, **kwargs) -> Any: ...
    def safeDownCast(self, obj: Object) -> Any: ...
    def setAllPropertiesUseDefault(self, *args, **kwargs) -> Any: ...
    def setAuthors(self, *args, **kwargs) -> Any: ...
    def setColumnLabels(self, *args, **kwargs) -> Any: ...
    def setComputeMoments(self, *args, **kwargs) -> Any: ...
    def setCoordinates(self, *args, **kwargs) -> Any: ...
    def setDebugLevel(self, *args, **kwargs) -> Any: ...
    def setDescription(self, *args, **kwargs) -> Any: ...
    def setEndTime(self, *args, **kwargs) -> Any: ...
    def setInDegrees(self, *args, **kwargs) -> Any: ...
    def setInlined(self, *args, **kwargs) -> Any: ...
    def setModel(self, *args, **kwargs) -> Any: ...
    def setMuscles(self, *args, **kwargs) -> Any: ...
    def setName(self, *args, **kwargs) -> Any: ...
    def setOn(self, *args, **kwargs) -> Any: ...
    def setPrintResultFiles(self, *args, **kwargs) -> Any: ...
    def setReferences(self, *args, **kwargs) -> Any: ...
    def setSerializeAllDefaults(self, *args, **kwargs) -> Any: ...
    def setStartTime(self, *args, **kwargs) -> Any: ...
    def setStatesStore(self, *args, **kwargs) -> Any: ...
    def setStepInterval(self, *args, **kwargs) -> Any: ...
    def setStorageCapacityIncrements(self, *args, **kwargs) -> Any: ...
    def step(self, s: State, setNumber: int) -> int: ...
    thisown: Any
    def toString(self) -> str: ...
    def updPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def updPropertyByName(self, name: str) -> Any: ...
    def updateFromXMLNode(self, *args, **kwargs) -> Any: ...
    def updateXMLNode(self, *args, **kwargs) -> Any: ...

class OutputReporter:
    def PrintPropertyInfo(self, os: Any, classNameDotPropertyName: str, printFlagInfo: bool) -> bool: ...
    @overload
    def PrintPropertyInfo(self, os: Any, className: str, propertyName: str, printFlagInfo: bool) -> bool: ...
    def RegisterType(self, *args, **kwargs) -> Any: ...
    def RenameType(self, *args, **kwargs) -> Any: ...
    def SafeCopy(self, aObject: Object) -> Any: ...
    def __init__(self, model: Model) -> None: ...
    @overload
    def __init__(self, fileName: str) -> None: ...
    def append_output_paths(self, value: str) -> int: ...
    def assign(self, *args, **kwargs) -> Any: ...
    def begin(self, s: State) -> int: ...
    def clone(self) -> Any: ...
    def constructProperty_output_paths(self, *args, **kwargs) -> Any: ...
    def copyProperty_output_paths(self, *args, **kwargs) -> Any: ...
    def dump(self) -> str: ...
    def end(self, s: State) -> int: ...
    def getAuthors(self) -> str: ...
    def getClassName(self) -> str: ...
    def getColumnLabels(self) -> Any: ...
    def getConcreteClassName(self) -> str: ...
    def getDebugLevel(self) -> int: ...
    def getDefaultInstanceOfType(self, concreteClassName: str) -> Any: ...
    def getDescription(self) -> str: ...
    def getDocumentFileName(self) -> str: ...
    def getDocumentFileVersion(self) -> int: ...
    def getEndTime(self) -> float: ...
    def getInDegrees(self) -> bool: ...
    def getInlined(self) -> bool: ...
    def getName(self) -> str: ...
    def getNumProperties(self) -> int: ...
    def getOn(self) -> bool: ...
    def getPrintResultFiles(self) -> bool: ...
    def getPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def getPropertyByName(self, name: str) -> Any: ...
    def getReferences(self) -> str: ...
    def getRegisteredTypenames(self, *args, **kwargs) -> Any: ...
    def getSerializeAllDefaults(self) -> bool: ...
    def getStartTime(self) -> float: ...
    def getStepInterval(self) -> int: ...
    def getStorageList(self) -> Any: ...
    def get_output_paths(self, i: int) -> str: ...
    def hasProperty(self, name: str) -> bool: ...
    def isA(self, type: str) -> bool: ...
    def isEqualTo(self, aObject: Object) -> bool: ...
    def isKindOf(self, type: str) -> bool: ...
    def isObjectUpToDateWithProperties(self) -> bool: ...
    def makeObjectFromFile(self, fileName: str) -> Any: ...
    def newInstanceOfType(self, concreteClassName: str) -> Any: ...
    def printResults(self, aBaseName: str, aDir: str, aDT: float, aExtension: str) -> int: ...
    def printToXML(self, fileName: str) -> bool: ...
    def proceed(self, aStep: int) -> bool: ...
    def readObjectFromXMLNodeOrFile(self, *args, **kwargs) -> Any: ...
    def registerType(self, *args, **kwargs) -> Any: ...
    def renameType(self, *args, **kwargs) -> Any: ...
    def safeDownCast(self, obj: Object) -> Any: ...
    def setAllPropertiesUseDefault(self, *args, **kwargs) -> Any: ...
    def setAuthors(self, *args, **kwargs) -> Any: ...
    def setColumnLabels(self, *args, **kwargs) -> Any: ...
    def setDebugLevel(self, *args, **kwargs) -> Any: ...
    def setDescription(self, *args, **kwargs) -> Any: ...
    def setEndTime(self, *args, **kwargs) -> Any: ...
    def setInDegrees(self, *args, **kwargs) -> Any: ...
    def setInlined(self, *args, **kwargs) -> Any: ...
    def setModel(self, *args, **kwargs) -> Any: ...
    def setName(self, *args, **kwargs) -> Any: ...
    def setOn(self, *args, **kwargs) -> Any: ...
    def setPrintResultFiles(self, *args, **kwargs) -> Any: ...
    def setReferences(self, *args, **kwargs) -> Any: ...
    def setSerializeAllDefaults(self, *args, **kwargs) -> Any: ...
    def setStartTime(self, *args, **kwargs) -> Any: ...
    def setStatesStore(self, *args, **kwargs) -> Any: ...
    def setStepInterval(self, *args, **kwargs) -> Any: ...
    def set_output_paths(self, *args, **kwargs) -> Any: ...
    def step(self, s: State, stepNumber: int) -> int: ...
    thisown: Any
    def toString(self) -> str: ...
    def updPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def updPropertyByName(self, name: str) -> Any: ...
    def upd_output_paths(self, i: int) -> Any: ...
    def updateFromXMLNode(self, *args, **kwargs) -> Any: ...
    def updateXMLNode(self, *args, **kwargs) -> Any: ...

class PointKinematics:
    BUFFER_LENGTH: Any
    NAME_LENGTH: Any
    def PrintPropertyInfo(self, os: Any, classNameDotPropertyName: str, printFlagInfo: bool) -> bool: ...
    @overload
    def PrintPropertyInfo(self, os: Any, className: str, propertyName: str, printFlagInfo: bool) -> bool: ...
    def RegisterType(self, *args, **kwargs) -> Any: ...
    def RenameType(self, *args, **kwargs) -> Any: ...
    def SafeCopy(self, aObject: Object) -> Any: ...
    def __init__(self, aModel: Model) -> None: ...
    @overload
    def __init__(self, aFileName: str) -> None: ...
    @overload
    def __init__(self, aObject: PointKinematics) -> None: ...
    def assign(self, *args, **kwargs) -> Any: ...
    def begin(self, s: State) -> int: ...
    def clone(self) -> Any: ...
    def dump(self) -> str: ...
    def end(self, s: State) -> int: ...
    def getAccelerationStorage(self) -> Any: ...
    def getAuthors(self) -> str: ...
    def getBody(self) -> Any: ...
    def getClassName(self) -> str: ...
    def getColumnLabels(self) -> Any: ...
    def getConcreteClassName(self) -> str: ...
    def getDebugLevel(self) -> int: ...
    def getDefaultInstanceOfType(self, concreteClassName: str) -> Any: ...
    def getDescription(self) -> str: ...
    def getDocumentFileName(self) -> str: ...
    def getDocumentFileVersion(self) -> int: ...
    def getEndTime(self) -> float: ...
    def getInDegrees(self) -> bool: ...
    def getInlined(self) -> bool: ...
    def getName(self) -> str: ...
    def getNumProperties(self) -> int: ...
    def getOn(self) -> bool: ...
    def getPoint(self, *args, **kwargs) -> Any: ...
    def getPointName(self) -> str: ...
    def getPositionStorage(self) -> Any: ...
    def getPrintResultFiles(self) -> bool: ...
    def getPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def getPropertyByName(self, name: str) -> Any: ...
    def getReferences(self) -> str: ...
    def getRegisteredTypenames(self, *args, **kwargs) -> Any: ...
    def getRelativeToBody(self) -> Any: ...
    def getSerializeAllDefaults(self) -> bool: ...
    def getStartTime(self) -> float: ...
    def getStepInterval(self) -> int: ...
    def getStorageList(self) -> Any: ...
    def getVelocityStorage(self) -> Any: ...
    def hasProperty(self, name: str) -> bool: ...
    def isA(self, type: str) -> bool: ...
    def isEqualTo(self, aObject: Object) -> bool: ...
    def isKindOf(self, type: str) -> bool: ...
    def isObjectUpToDateWithProperties(self) -> bool: ...
    def makeObjectFromFile(self, fileName: str) -> Any: ...
    def newInstanceOfType(self, concreteClassName: str) -> Any: ...
    def printResults(self, aBaseName: str, aDir: str, aDT: float, aExtension: str) -> int: ...
    def printToXML(self, fileName: str) -> bool: ...
    def proceed(self, aStep: int) -> bool: ...
    def readObjectFromXMLNodeOrFile(self, *args, **kwargs) -> Any: ...
    def registerType(self, *args, **kwargs) -> Any: ...
    def renameType(self, *args, **kwargs) -> Any: ...
    def safeDownCast(self, obj: Object) -> Any: ...
    def setAllPropertiesUseDefault(self, *args, **kwargs) -> Any: ...
    def setAuthors(self, *args, **kwargs) -> Any: ...
    def setBody(self, *args, **kwargs) -> Any: ...
    def setBodyPoint(self, *args, **kwargs) -> Any: ...
    def setColumnLabels(self, *args, **kwargs) -> Any: ...
    def setDebugLevel(self, *args, **kwargs) -> Any: ...
    def setDescription(self, *args, **kwargs) -> Any: ...
    def setEndTime(self, *args, **kwargs) -> Any: ...
    def setInDegrees(self, *args, **kwargs) -> Any: ...
    def setInlined(self, *args, **kwargs) -> Any: ...
    def setModel(self, *args, **kwargs) -> Any: ...
    def setName(self, *args, **kwargs) -> Any: ...
    def setOn(self, *args, **kwargs) -> Any: ...
    def setPoint(self, *args, **kwargs) -> Any: ...
    def setPointName(self, *args, **kwargs) -> Any: ...
    def setPrintResultFiles(self, *args, **kwargs) -> Any: ...
    def setReferences(self, *args, **kwargs) -> Any: ...
    def setRelativeToBody(self, *args, **kwargs) -> Any: ...
    def setSerializeAllDefaults(self, *args, **kwargs) -> Any: ...
    def setStartTime(self, *args, **kwargs) -> Any: ...
    def setStatesStore(self, *args, **kwargs) -> Any: ...
    def setStepInterval(self, *args, **kwargs) -> Any: ...
    def setStorageCapacityIncrements(self, *args, **kwargs) -> Any: ...
    def step(self, s: State, setNumber: int) -> int: ...
    thisown: Any
    def toString(self) -> str: ...
    def updPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def updPropertyByName(self, name: str) -> Any: ...
    def updateFromXMLNode(self, *args, **kwargs) -> Any: ...
    def updateXMLNode(self, *args, **kwargs) -> Any: ...

class ProbeReporter:
    def PrintPropertyInfo(self, os: Any, classNameDotPropertyName: str, printFlagInfo: bool) -> bool: ...
    @overload
    def PrintPropertyInfo(self, os: Any, className: str, propertyName: str, printFlagInfo: bool) -> bool: ...
    def RegisterType(self, *args, **kwargs) -> Any: ...
    def RenameType(self, *args, **kwargs) -> Any: ...
    def SafeCopy(self, aObject: Object) -> Any: ...
    def __init__(self, aModel: Model) -> None: ...
    @overload
    def __init__(self, aFileName: str) -> None: ...
    @overload
    def __init__(self, aObject: ProbeReporter) -> None: ...
    def assign(self, *args, **kwargs) -> Any: ...
    def begin(self, s: State) -> int: ...
    def clone(self) -> Any: ...
    def disableIntegrationOnlyProbes(self, *args, **kwargs) -> Any: ...
    def dump(self) -> str: ...
    def end(self, s: State) -> int: ...
    def getAuthors(self) -> str: ...
    def getClassName(self) -> str: ...
    def getColumnLabels(self) -> Any: ...
    def getConcreteClassName(self) -> str: ...
    def getDebugLevel(self) -> int: ...
    def getDefaultInstanceOfType(self, concreteClassName: str) -> Any: ...
    def getDescription(self) -> str: ...
    def getDocumentFileName(self) -> str: ...
    def getDocumentFileVersion(self) -> int: ...
    def getEndTime(self) -> float: ...
    def getInDegrees(self) -> bool: ...
    def getInlined(self) -> bool: ...
    def getName(self) -> str: ...
    def getNumProperties(self) -> int: ...
    def getOn(self) -> bool: ...
    def getPrintResultFiles(self) -> bool: ...
    def getProbeStorage(self) -> Any: ...
    def getPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def getPropertyByName(self, name: str) -> Any: ...
    def getReferences(self) -> str: ...
    def getRegisteredTypenames(self, *args, **kwargs) -> Any: ...
    def getSerializeAllDefaults(self) -> bool: ...
    def getStartTime(self) -> float: ...
    def getStepInterval(self) -> int: ...
    def getStorageList(self) -> Any: ...
    def hasProperty(self, name: str) -> bool: ...
    def isA(self, type: str) -> bool: ...
    def isEqualTo(self, aObject: Object) -> bool: ...
    def isKindOf(self, type: str) -> bool: ...
    def isObjectUpToDateWithProperties(self) -> bool: ...
    def makeObjectFromFile(self, fileName: str) -> Any: ...
    def newInstanceOfType(self, concreteClassName: str) -> Any: ...
    def printResults(self, aBaseName: str, aDir: str, aDT: float, aExtension: str) -> int: ...
    def printToXML(self, fileName: str) -> bool: ...
    def proceed(self, aStep: int) -> bool: ...
    def readObjectFromXMLNodeOrFile(self, *args, **kwargs) -> Any: ...
    def registerType(self, *args, **kwargs) -> Any: ...
    def renameType(self, *args, **kwargs) -> Any: ...
    def safeDownCast(self, obj: Object) -> Any: ...
    def setAllPropertiesUseDefault(self, *args, **kwargs) -> Any: ...
    def setAuthors(self, *args, **kwargs) -> Any: ...
    def setColumnLabels(self, *args, **kwargs) -> Any: ...
    def setDebugLevel(self, *args, **kwargs) -> Any: ...
    def setDescription(self, *args, **kwargs) -> Any: ...
    def setEndTime(self, *args, **kwargs) -> Any: ...
    def setInDegrees(self, *args, **kwargs) -> Any: ...
    def setInlined(self, *args, **kwargs) -> Any: ...
    def setModel(self, *args, **kwargs) -> Any: ...
    def setName(self, *args, **kwargs) -> Any: ...
    def setOn(self, *args, **kwargs) -> Any: ...
    def setPrintResultFiles(self, *args, **kwargs) -> Any: ...
    def setReferences(self, *args, **kwargs) -> Any: ...
    def setSerializeAllDefaults(self, *args, **kwargs) -> Any: ...
    def setStartTime(self, *args, **kwargs) -> Any: ...
    def setStatesStore(self, *args, **kwargs) -> Any: ...
    def setStepInterval(self, *args, **kwargs) -> Any: ...
    def step(self, s: State, setNumber: int) -> int: ...
    thisown: Any
    def toString(self) -> str: ...
    def updProbeStorage(self) -> Any: ...
    def updPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def updPropertyByName(self, name: str) -> Any: ...
    def updateFromXMLNode(self, *args, **kwargs) -> Any: ...
    def updateXMLNode(self, *args, **kwargs) -> Any: ...

class StatesReporter:
    def PrintPropertyInfo(self, os: Any, classNameDotPropertyName: str, printFlagInfo: bool) -> bool: ...
    @overload
    def PrintPropertyInfo(self, os: Any, className: str, propertyName: str, printFlagInfo: bool) -> bool: ...
    def RegisterType(self, *args, **kwargs) -> Any: ...
    def RenameType(self, *args, **kwargs) -> Any: ...
    def SafeCopy(self, aObject: Object) -> Any: ...
    def __init__(self, aModel: Model) -> None: ...
    @overload
    def __init__(self, aFileName: str) -> None: ...
    @overload
    def __init__(self, aObject: StatesReporter) -> None: ...
    def assign(self, *args, **kwargs) -> Any: ...
    def begin(self, s: State) -> int: ...
    def clone(self) -> Any: ...
    def dump(self) -> str: ...
    def end(self, s: State) -> int: ...
    def getAuthors(self) -> str: ...
    def getClassName(self) -> str: ...
    def getColumnLabels(self) -> Any: ...
    def getConcreteClassName(self) -> str: ...
    def getDebugLevel(self) -> int: ...
    def getDefaultInstanceOfType(self, concreteClassName: str) -> Any: ...
    def getDescription(self) -> str: ...
    def getDocumentFileName(self) -> str: ...
    def getDocumentFileVersion(self) -> int: ...
    def getEndTime(self) -> float: ...
    def getInDegrees(self) -> bool: ...
    def getInlined(self) -> bool: ...
    def getName(self) -> str: ...
    def getNumProperties(self) -> int: ...
    def getOn(self) -> bool: ...
    def getPrintResultFiles(self) -> bool: ...
    def getPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def getPropertyByName(self, name: str) -> Any: ...
    def getReferences(self) -> str: ...
    def getRegisteredTypenames(self, *args, **kwargs) -> Any: ...
    def getSerializeAllDefaults(self) -> bool: ...
    def getStartTime(self) -> float: ...
    def getStatesStorage(self) -> Any: ...
    def getStepInterval(self) -> int: ...
    def getStorageList(self) -> Any: ...
    def hasProperty(self, name: str) -> bool: ...
    def isA(self, type: str) -> bool: ...
    def isEqualTo(self, aObject: Object) -> bool: ...
    def isKindOf(self, type: str) -> bool: ...
    def isObjectUpToDateWithProperties(self) -> bool: ...
    def makeObjectFromFile(self, fileName: str) -> Any: ...
    def newInstanceOfType(self, concreteClassName: str) -> Any: ...
    def printResults(self, aBaseName: str, aDir: str, aDT: float, aExtension: str) -> int: ...
    def printToXML(self, fileName: str) -> bool: ...
    def proceed(self, aStep: int) -> bool: ...
    def readObjectFromXMLNodeOrFile(self, *args, **kwargs) -> Any: ...
    def registerType(self, *args, **kwargs) -> Any: ...
    def renameType(self, *args, **kwargs) -> Any: ...
    def safeDownCast(self, obj: Object) -> Any: ...
    def setAllPropertiesUseDefault(self, *args, **kwargs) -> Any: ...
    def setAuthors(self, *args, **kwargs) -> Any: ...
    def setColumnLabels(self, *args, **kwargs) -> Any: ...
    def setDebugLevel(self, *args, **kwargs) -> Any: ...
    def setDescription(self, *args, **kwargs) -> Any: ...
    def setEndTime(self, *args, **kwargs) -> Any: ...
    def setInDegrees(self, *args, **kwargs) -> Any: ...
    def setInlined(self, *args, **kwargs) -> Any: ...
    def setModel(self, *args, **kwargs) -> Any: ...
    def setName(self, *args, **kwargs) -> Any: ...
    def setOn(self, *args, **kwargs) -> Any: ...
    def setPrintResultFiles(self, *args, **kwargs) -> Any: ...
    def setReferences(self, *args, **kwargs) -> Any: ...
    def setSerializeAllDefaults(self, *args, **kwargs) -> Any: ...
    def setStartTime(self, *args, **kwargs) -> Any: ...
    def setStatesStore(self, *args, **kwargs) -> Any: ...
    def setStepInterval(self, *args, **kwargs) -> Any: ...
    def step(self, s: State, setNumber: int) -> int: ...
    thisown: Any
    def toString(self) -> str: ...
    def updPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def updPropertyByName(self, name: str) -> Any: ...
    def updStatesStorage(self) -> Any: ...
    def updateFromXMLNode(self, *args, **kwargs) -> Any: ...
    def updateXMLNode(self, *args, **kwargs) -> Any: ...

class StaticOptimization:
    def PrintPropertyInfo(self, os: Any, classNameDotPropertyName: str, printFlagInfo: bool) -> bool: ...
    @overload
    def PrintPropertyInfo(self, os: Any, className: str, propertyName: str, printFlagInfo: bool) -> bool: ...
    def RegisterType(self, *args, **kwargs) -> Any: ...
    def RenameType(self, *args, **kwargs) -> Any: ...
    def SafeCopy(self, aObject: Object) -> Any: ...
    def __init__(self, aModel: Model) -> None: ...
    @overload
    def __init__(self, aObject: StaticOptimization) -> None: ...
    def assign(self, *args, **kwargs) -> Any: ...
    def begin(self, s: State) -> int: ...
    def clone(self) -> Any: ...
    def dump(self) -> str: ...
    def end(self, s: State) -> int: ...
    def getActivationExponent(self) -> float: ...
    def getActivationStorage(self) -> Any: ...
    def getAuthors(self) -> str: ...
    def getClassName(self) -> str: ...
    def getColumnLabels(self) -> Any: ...
    def getConcreteClassName(self) -> str: ...
    def getConvergenceCriterion(self) -> float: ...
    def getDebugLevel(self) -> int: ...
    def getDefaultInstanceOfType(self, concreteClassName: str) -> Any: ...
    def getDescription(self) -> str: ...
    def getDocumentFileName(self) -> str: ...
    def getDocumentFileVersion(self) -> int: ...
    def getEndTime(self) -> float: ...
    def getForceStorage(self) -> Any: ...
    def getInDegrees(self) -> bool: ...
    def getInlined(self) -> bool: ...
    def getMaxIterations(self) -> int: ...
    def getName(self) -> str: ...
    def getNumProperties(self) -> int: ...
    def getOn(self) -> bool: ...
    def getPrintResultFiles(self) -> bool: ...
    def getPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def getPropertyByName(self, name: str) -> Any: ...
    def getReferences(self) -> str: ...
    def getRegisteredTypenames(self, *args, **kwargs) -> Any: ...
    def getSerializeAllDefaults(self) -> bool: ...
    def getStartTime(self) -> float: ...
    def getStatesDerivativeStore(self) -> Any: ...
    def getStepInterval(self) -> int: ...
    def getStorageList(self) -> Any: ...
    def getUseModelForceSet(self) -> bool: ...
    def getUseMusclePhysiology(self) -> bool: ...
    def hasProperty(self, name: str) -> bool: ...
    def isA(self, type: str) -> bool: ...
    def isEqualTo(self, aObject: Object) -> bool: ...
    def isKindOf(self, type: str) -> bool: ...
    def isObjectUpToDateWithProperties(self) -> bool: ...
    def makeObjectFromFile(self, fileName: str) -> Any: ...
    def newInstanceOfType(self, concreteClassName: str) -> Any: ...
    def printResults(self, aBaseName: str, aDir: str, aDT: float, aExtension: str) -> int: ...
    def printToXML(self, fileName: str) -> bool: ...
    def proceed(self, aStep: int) -> bool: ...
    def readObjectFromXMLNodeOrFile(self, *args, **kwargs) -> Any: ...
    def registerType(self, *args, **kwargs) -> Any: ...
    def renameType(self, *args, **kwargs) -> Any: ...
    def safeDownCast(self, obj: Object) -> Any: ...
    def setActivationExponent(self, *args, **kwargs) -> Any: ...
    def setAllPropertiesUseDefault(self, *args, **kwargs) -> Any: ...
    def setAuthors(self, *args, **kwargs) -> Any: ...
    def setColumnLabels(self, *args, **kwargs) -> Any: ...
    def setConvergenceCriterion(self, *args, **kwargs) -> Any: ...
    def setDebugLevel(self, *args, **kwargs) -> Any: ...
    def setDescription(self, *args, **kwargs) -> Any: ...
    def setEndTime(self, *args, **kwargs) -> Any: ...
    def setInDegrees(self, *args, **kwargs) -> Any: ...
    def setInlined(self, *args, **kwargs) -> Any: ...
    def setMaxIterations(self, *args, **kwargs) -> Any: ...
    def setModel(self, *args, **kwargs) -> Any: ...
    def setName(self, *args, **kwargs) -> Any: ...
    def setOn(self, *args, **kwargs) -> Any: ...
    def setPrintResultFiles(self, *args, **kwargs) -> Any: ...
    def setReferences(self, *args, **kwargs) -> Any: ...
    def setSerializeAllDefaults(self, *args, **kwargs) -> Any: ...
    def setStartTime(self, *args, **kwargs) -> Any: ...
    def setStatesStore(self, *args, **kwargs) -> Any: ...
    def setStepInterval(self, *args, **kwargs) -> Any: ...
    def setStorageCapacityIncrements(self, *args, **kwargs) -> Any: ...
    def setUseModelForceSet(self, *args, **kwargs) -> Any: ...
    def setUseMusclePhysiology(self, *args, **kwargs) -> Any: ...
    def step(self, s: State, setNumber: int) -> int: ...
    thisown: Any
    def toString(self) -> str: ...
    def updPropertyByIndex(self, propertyIndex: int) -> Any: ...
    def updPropertyByName(self, name: str) -> Any: ...
    def updateFromXMLNode(self, *args, **kwargs) -> Any: ...
    def updateXMLNode(self, *args, **kwargs) -> Any: ...

class SwigPyIterator:
    def __init__(self, *args, **kwargs) -> Any: ...
    def advance(self, n: Any) -> Any: ...
    def copy(self) -> Any: ...
    def decr(self, n: Any) -> Any: ...
    def distance(self, x: Any) -> Any: ...
    def equal(self, x: Any) -> bool: ...
    def incr(self, n: Any) -> Any: ...
    def next(self) -> Any: ...
    def previous(self) -> Any: ...
    thisown: Any
    def value(self) -> Any: ...

