from .core.serialmixin import NumpyArrayNotSerializableError as NumpyArrayNotSerializableError
from .util.checks import NONE as NONE
from .util.exception import AnalyticGradientNotAvailable as AnalyticGradientNotAvailable, AnalyticIntegralNotImplemented as AnalyticIntegralNotImplemented, AnalyticNotImplemented as AnalyticNotImplemented, AnalyticSamplingNotImplemented as AnalyticSamplingNotImplemented, FunctionNotImplemented as FunctionNotImplemented, IllegalInGraphModeError as IllegalInGraphModeError, InitNotImplemented as InitNotImplemented, LogicalUndefinedOperationError as LogicalUndefinedOperationError, MaximumIterationReached as MaximumIterationReached, MinimizerSubclassingError as MinimizerSubclassingError, MultipleLimitsNotImplemented as MultipleLimitsNotImplemented, NormRangeNotImplemented as NormRangeNotImplemented, ParamNameNotUniqueError as ParamNameNotUniqueError, ShapeIncompatibleError as ShapeIncompatibleError, SpecificFunctionNotImplemented as SpecificFunctionNotImplemented, VectorizedLimitsNotImplemented as VectorizedLimitsNotImplemented

__all__ = ['NONE', 'AnalyticGradientNotAvailable', 'AnalyticIntegralNotImplemented', 'AnalyticNotImplemented', 'AnalyticSamplingNotImplemented', 'FunctionNotImplemented', 'IllegalInGraphModeError', 'InitNotImplemented', 'InvalidNameError', 'IpyoptPicklingError', 'LogicalUndefinedOperationError', 'MaximumIterationReached', 'MinimizerSubclassingError', 'MultipleLimitsNotImplemented', 'NameAlreadyTakenError', 'NormRangeNotImplemented', 'NumpyArrayNotSerializableError', 'ParamNameNotUniqueError', 'ShapeIncompatibleError', 'SpecificFunctionNotImplemented', 'VectorizedLimitsNotImplemented']

class InvalidNameError(Exception): ...

class NameAlreadyTakenError(Exception):
    def __init__(self, *_: object) -> None: ...

class IpyoptPicklingError(TypeError): ...
class OutsideLimitsError(Exception): ...
class AutogradNotSupported(Exception): ...
