"""This module lists all required environment variables used by DISCOVER

Author:
    Dominik Schiller <dominik.schiller@uni-a.de>
Date:
    13.09.2023

"""
# DISCOVER
DISCOVER_HOST = "DISCOVER_HOST"
DISCOVER_PORT = "DISCOVER_PORT"
DISCOVER_CML_DIR = "DISCOVER_CML_DIR"
DISCOVER_DATA_DIR = "DISCOVER_DATA_DIR"
DISCOVER_CACHE_DIR = "DISCOVER_CACHE_DIR"
DISCOVER_TMP_DIR = "DISCOVER_TMP_DIR"
DISCOVER_LOG_DIR = "DISCOVER_LOG_DIR"
DISCOVER_BACKEND = "DISCOVER_BACKEND"
DISCOVER_VIDEO_BACKEND = "DISCOVER_VIDEO_BACKEND"
DISCOVER_USE_TLS = "DISCOVER_USE_TLS"

# BACKENDS
VENV_FORCE_UPDATE = "VENV_FORCE_UPDATE"
VENV_LOG_VERBOSE = "VENV_LOG_VERBOSE"
VENV_EXTRA_INDEX_URLS = "VENV_EXTRA_INDEX_URLS"