from .auth import router as auth_router
from .camera import router as camera_router
from .chat import router as chat_router
from .control import router as control_router
from .networking import router as networking_router
from .pages import router as pages_router
from .recording import router as recording_router
from .training import router as training_router
from .update import router as update_router
