from functools import lru_cache
import json
import uuid
from typing import Optional, Union, Dict, Callable, List
from ...common.ui_functions import clear_layout
from qtpy.QtWidgets import QGridLayout, QFrame, QHBoxLayout, QWidget, QSizePolicy, QVBoxLayout
from qtpy.QtCore import Qt
from qtmui.hooks.use_state import State
from ..typography import Typography
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.material.styles import useTheme
from ...utils.data import convert_sx_params_to_str, convert_sx_params_to_dict
from ..utils.validate_params import validate_bool, validate_non_negative_number, validate_positive_integer, validate_spacing, validate_sx, validate_string, validate_choice, validate_dict_with_positive_integers, validate_children, validate_param
from ..widget_base import PyWidgetBase
class Grid:
    def __init__(self, container: Optional[Union[bool, State]], key: Optional[Union[str, State]], columns: Optional[Union[int, Dict, List, State]], columnSpacing: Optional[Union[int, str, Dict, List, State]], direction: Optional[Union[str, Dict, List, State]], offset: Optional[Union[int, str, Dict, List, State]], spacing: Optional[Union[int, str, Dict, List, State]], wrap: Optional[Union[str, State]], children: Optional[Union[str, Callable, list, State]], rowSpacing: Optional[Union[int, str, Dict, List, State]], size: Optional[Union[int, str, Dict, List, State]], sx: Optional[Union[State, Callable, str, Dict]]): ...
    def _validate_initial_params(self): ...
    def _set_container(self, value): ...
    def _set_key(self, value): ...
    def _set_columns(self, value): ...
    def _set_columnSpacing(self, value): ...
    def _set_direction(self, value): ...
    def _set_offset(self, value): ...
    def _set_spacing(self, value): ...
    def _set_wrap(self, value): ...
    def _set_children(self, value): ...
    def _set_rowSpacing(self, value): ...
    def _set_size(self, value): ...
    def _set_sx(self, value): ...
    def _on_destroyed(self): ...
    def _connect_signals(self): ...
    def _on_container_changed(self): ...
    def _on_key_changed(self): ...
    def _on_columns_changed(self): ...
    def _on_columnSpacing_changed(self): ...
    def _on_direction_changed(self): ...
    def _on_offset_changed(self): ...
    def _on_spacing_changed(self): ...
    def _on_wrap_changed(self): ...
    def _on_children_changed(self): ...
    def _on_rowSpacing_changed(self): ...
    def _on_size_changed(self): ...
    def _on_sx_changed(self): ...
    def _init_ui(self): ...
    def _setup_layout(self): ...
    def _set_stylesheet(self, component_styled): ...
    def _get_breakpoint(self): ...
    def _get_columns_by_breakpoint(self, breakpoint: str, columns: Union[int, Dict, List]): ...
    def _add_columns_by_breakpoint(self, breakpoint: str, size: Union[int, Dict, List]): ...
    def _get_offset_by_breakpoint(self, breakpoint: str, offset: Union[int, Dict, List]): ...
    def _arrange_children(self): ...
    def resizeEvent(self, event): ...