# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admobilize/mlmodel/v1alpha1/mlmodel_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from admobilize.proto.common import entity_pb2 as admobilize_dot_common_dot_entity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1admobilize/mlmodel/v1alpha1/mlmodel_service.proto\x12\x1b\x61\x64mobilize.mlmodel.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1e\x61\x64mobilize/common/entity.proto\"@\n\x13\x43reateModelsRequest\x12)\n\x06models\x18\x01 \x03(\x0b\x32\x19.admobilize.common.Entity\"m\n\x10GetModelsRequest\x12)\n\x06models\x18\x01 \x03(\x0b\x32\x19.admobilize.common.Entity\x12.\n\nfield_mask\x18\n \x01(\x0b\x32\x1a.google.protobuf.FieldMask\">\n\x11GetModelsResponse\x12)\n\x06models\x18\x01 \x03(\x0b\x32\x19.admobilize.common.Entity\"@\n\x13\x44\x65leteModelsRequest\x12)\n\x06models\x18\x01 \x03(\x0b\x32\x19.admobilize.common.Entity2\x9a\x03\n\x0eMLModelService\x12|\n\x0c\x43reateModels\x12\x30.admobilize.mlmodel.v1alpha1.CreateModelsRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c\"\x17/v1alpha1/models:create:\x01*\x12\x8b\x01\n\tGetModels\x12-.admobilize.mlmodel.v1alpha1.GetModelsRequest\x1a..admobilize.mlmodel.v1alpha1.GetModelsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x14/v1alpha1/models:get:\x01*\x12|\n\x0c\x44\x65leteModels\x12\x30.admobilize.mlmodel.v1alpha1.DeleteModelsRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c\"\x17/v1alpha1/models:delete:\x01*B\x98\x01\n\x1f\x63om.admobilize.mlmodel.v1alpha1B\x0cMLModelProtoP\x01Z?bitbucket.org/admobilize/admobilizeapis-go/pkg/mlmodel/v1alpha1\xa2\x02\x05\x41\x44MML\xaa\x02\x1b\x41\x64Mobilize.MLModel.V1Alpha1b\x06proto3')



_CREATEMODELSREQUEST = DESCRIPTOR.message_types_by_name['CreateModelsRequest']
_GETMODELSREQUEST = DESCRIPTOR.message_types_by_name['GetModelsRequest']
_GETMODELSRESPONSE = DESCRIPTOR.message_types_by_name['GetModelsResponse']
_DELETEMODELSREQUEST = DESCRIPTOR.message_types_by_name['DeleteModelsRequest']
CreateModelsRequest = _reflection.GeneratedProtocolMessageType('CreateModelsRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEMODELSREQUEST,
  '__module__' : 'admobilize.mlmodel.v1alpha1.mlmodel_service_pb2'
  # @@protoc_insertion_point(class_scope:admobilize.mlmodel.v1alpha1.CreateModelsRequest)
  })
_sym_db.RegisterMessage(CreateModelsRequest)

GetModelsRequest = _reflection.GeneratedProtocolMessageType('GetModelsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMODELSREQUEST,
  '__module__' : 'admobilize.mlmodel.v1alpha1.mlmodel_service_pb2'
  # @@protoc_insertion_point(class_scope:admobilize.mlmodel.v1alpha1.GetModelsRequest)
  })
_sym_db.RegisterMessage(GetModelsRequest)

GetModelsResponse = _reflection.GeneratedProtocolMessageType('GetModelsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETMODELSRESPONSE,
  '__module__' : 'admobilize.mlmodel.v1alpha1.mlmodel_service_pb2'
  # @@protoc_insertion_point(class_scope:admobilize.mlmodel.v1alpha1.GetModelsResponse)
  })
_sym_db.RegisterMessage(GetModelsResponse)

DeleteModelsRequest = _reflection.GeneratedProtocolMessageType('DeleteModelsRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEMODELSREQUEST,
  '__module__' : 'admobilize.mlmodel.v1alpha1.mlmodel_service_pb2'
  # @@protoc_insertion_point(class_scope:admobilize.mlmodel.v1alpha1.DeleteModelsRequest)
  })
_sym_db.RegisterMessage(DeleteModelsRequest)

_MLMODELSERVICE = DESCRIPTOR.services_by_name['MLModelService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037com.admobilize.mlmodel.v1alpha1B\014MLModelProtoP\001Z?bitbucket.org/admobilize/admobilizeapis-go/pkg/mlmodel/v1alpha1\242\002\005ADMML\252\002\033AdMobilize.MLModel.V1Alpha1'
  _MLMODELSERVICE.methods_by_name['CreateModels']._options = None
  _MLMODELSERVICE.methods_by_name['CreateModels']._serialized_options = b'\202\323\344\223\002\034\"\027/v1alpha1/models:create:\001*'
  _MLMODELSERVICE.methods_by_name['GetModels']._options = None
  _MLMODELSERVICE.methods_by_name['GetModels']._serialized_options = b'\202\323\344\223\002\031\"\024/v1alpha1/models:get:\001*'
  _MLMODELSERVICE.methods_by_name['DeleteModels']._options = None
  _MLMODELSERVICE.methods_by_name['DeleteModels']._serialized_options = b'\202\323\344\223\002\034\"\027/v1alpha1/models:delete:\001*'
  _CREATEMODELSREQUEST._serialized_start=207
  _CREATEMODELSREQUEST._serialized_end=271
  _GETMODELSREQUEST._serialized_start=273
  _GETMODELSREQUEST._serialized_end=382
  _GETMODELSRESPONSE._serialized_start=384
  _GETMODELSRESPONSE._serialized_end=446
  _DELETEMODELSREQUEST._serialized_start=448
  _DELETEMODELSREQUEST._serialized_end=512
  _MLMODELSERVICE._serialized_start=515
  _MLMODELSERVICE._serialized_end=925
# @@protoc_insertion_point(module_scope)
