from typing import Optional, Tuple

from dev.coatl.helper.types import AnyStr

def getUserRoles(
    username: AnyStr, password: AnyStr, authProfile: AnyStr = ..., timeout: int = ...
) -> Optional[Tuple[AnyStr, ...]]: ...
def validateUser(
    username: AnyStr, password: AnyStr, authProfile: AnyStr = ..., timeout: int = ...
) -> bool: ...
