from typing import Any, Callable, Dict, List, Optional

from com.inductiveautomation.ignition.common.browsing import Results
from com.inductiveautomation.ignition.common.model.values import (
    BasicQualifiedValue,
    QualityCode,
)
from dev.coatl.helper.types import AnyStr

DEFAULT_TIMEOUT_MILLIS: int
LEGACY_DEFAULT_TIMEOUT_MILLIS: int
TAG_PATH: Any

def browse(path: AnyStr, filter: Optional[Dict[AnyStr, Any]] = ...) -> Results: ...
def configure(
    basePath: AnyStr, tags: List[Dict[AnyStr, Any]], collisionPolicy: AnyStr = ...
) -> List[QualityCode]: ...
def copy(
    tags: List[AnyStr], destination: AnyStr, collisionPolicy: AnyStr = ...
) -> List[QualityCode]: ...
def deleteTags(tagPaths: List[AnyStr]) -> List[QualityCode]: ...
def exists(tagPath: AnyStr) -> bool: ...
def exportTags(
    filePath: Optional[AnyStr] = ...,
    tagPaths: Optional[List[AnyStr]] = ...,
    recursive: bool = ...,
    exportType: AnyStr = ...,
) -> Optional[AnyStr]: ...
def getConfiguration(
    basePath: AnyStr, recursive: bool = ...
) -> List[Dict[AnyStr, Any]]: ...
def importTags(
    filePath: AnyStr, basePath: AnyStr, collisionPolicy: AnyStr = ...
) -> List[QualityCode]: ...
def move(
    tags: List[AnyStr], destination: AnyStr, collisionPolicy: AnyStr = ...
) -> List[QualityCode]: ...
def query(
    provider: Optional[AnyStr] = ...,
    query: Optional[Dict[AnyStr, Any]] = ...,
    limit: Optional[int] = ...,
    continuation: Optional[AnyStr] = ...,
) -> Results: ...
def readAsync(tagPaths: List[AnyStr], callback: Callable[..., Any]) -> None: ...
def readBlocking(
    tagPaths: List[AnyStr], timeout: int = ...
) -> List[BasicQualifiedValue]: ...
def rename(
    tag: AnyStr, newName: AnyStr, collisionPollicy: AnyStr = ...
) -> QualityCode: ...
def requestGroupExecution(provider: AnyStr, tagGroup: AnyStr) -> None: ...
def restartProvider(provider: AnyStr) -> bool: ...
def writeAsync(
    tagPaths: List[AnyStr],
    values: List[Any],
    callback: Optional[Callable[..., Any]] = ...,
) -> None: ...
def writeBlocking(
    tagPaths: List[AnyStr], values: List[Any], timeout: int = ...
) -> List[QualityCode]: ...
