# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from clavata.gateway.v1 import policies_pb2 as clavata_dot_gateway_dot_v1_dot_policies__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in clavata/gateway/v1/policies_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PoliciesServiceStub(object):
    """------------ POLICIES ------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPolicy = channel.unary_unary(
                '/clavata.gateway.v1.PoliciesService/GetPolicy',
                request_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GetPolicyRequest.SerializeToString,
                response_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GetPolicyResponse.FromString,
                _registered_method=True)
        self.GetPolicies = channel.unary_unary(
                '/clavata.gateway.v1.PoliciesService/GetPolicies',
                request_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GetPoliciesRequest.SerializeToString,
                response_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GetPoliciesResponse.FromString,
                _registered_method=True)
        self.UpdatePolicy = channel.unary_unary(
                '/clavata.gateway.v1.PoliciesService/UpdatePolicy',
                request_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.UpdatePolicyRequest.SerializeToString,
                response_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.UpdatePolicyResponse.FromString,
                _registered_method=True)
        self.GetPolicyVersions = channel.unary_unary(
                '/clavata.gateway.v1.PoliciesService/GetPolicyVersions',
                request_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GetPolicyVersionsRequest.SerializeToString,
                response_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GetPolicyVersionsResponse.FromString,
                _registered_method=True)
        self.GetActivePolicyVersions = channel.unary_unary(
                '/clavata.gateway.v1.PoliciesService/GetActivePolicyVersions',
                request_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GetActivePolicyVersionsRequest.SerializeToString,
                response_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GetActivePolicyVersionsResponse.FromString,
                _registered_method=True)
        self.DeletePolicy = channel.unary_unary(
                '/clavata.gateway.v1.PoliciesService/DeletePolicy',
                request_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.DeletePolicyRequest.SerializeToString,
                response_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.DeletePolicyResponse.FromString,
                _registered_method=True)
        self.UndeletePolicy = channel.unary_unary(
                '/clavata.gateway.v1.PoliciesService/UndeletePolicy',
                request_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.UndeletePolicyRequest.SerializeToString,
                response_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.UndeletePolicyResponse.FromString,
                _registered_method=True)
        self.SetActivePolicyVersion = channel.unary_unary(
                '/clavata.gateway.v1.PoliciesService/SetActivePolicyVersion',
                request_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.SetActivePolicyVersionRequest.SerializeToString,
                response_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.SetActivePolicyVersionResponse.FromString,
                _registered_method=True)
        self.ExpungePolicyVersion = channel.unary_unary(
                '/clavata.gateway.v1.PoliciesService/ExpungePolicyVersion',
                request_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.ExpungePolicyVersionRequest.SerializeToString,
                response_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.ExpungePolicyVersionResponse.FromString,
                _registered_method=True)
        self.UnexpungePolicyVersion = channel.unary_unary(
                '/clavata.gateway.v1.PoliciesService/UnexpungePolicyVersion',
                request_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.UnexpungePolicyVersionRequest.SerializeToString,
                response_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.UnexpungePolicyVersionResponse.FromString,
                _registered_method=True)
        self.ValidatePolicy = channel.unary_unary(
                '/clavata.gateway.v1.PoliciesService/ValidatePolicy',
                request_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.ValidatePolicyRequest.SerializeToString,
                response_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.ValidatePolicyResponse.FromString,
                _registered_method=True)
        self.TestPolicyWithDatasetItems = channel.unary_stream(
                '/clavata.gateway.v1.PoliciesService/TestPolicyWithDatasetItems',
                request_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.TestPolicyWithDatasetItemsRequest.SerializeToString,
                response_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.TestPolicyResponse.FromString,
                _registered_method=True)
        self.TestPolicy = channel.unary_stream(
                '/clavata.gateway.v1.PoliciesService/TestPolicy',
                request_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.TestPolicyRequest.SerializeToString,
                response_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.TestPolicyResponse.FromString,
                _registered_method=True)
        self.CreatePolicy = channel.unary_unary(
                '/clavata.gateway.v1.PoliciesService/CreatePolicy',
                request_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.CreatePolicyRequest.SerializeToString,
                response_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.CreatePolicyResponse.FromString,
                _registered_method=True)
        self.CreatePolicyVersion = channel.unary_unary(
                '/clavata.gateway.v1.PoliciesService/CreatePolicyVersion',
                request_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.CreatePolicyVersionRequest.SerializeToString,
                response_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.CreatePolicyVersionResponse.FromString,
                _registered_method=True)
        self.GeneratePolicyFromDataset = channel.unary_unary(
                '/clavata.gateway.v1.PoliciesService/GeneratePolicyFromDataset',
                request_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GeneratePolicyFromDatasetRequest.SerializeToString,
                response_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GeneratePolicyFromDatasetResponse.FromString,
                _registered_method=True)
        self.ListGeneratePolicyTasks = channel.unary_unary(
                '/clavata.gateway.v1.PoliciesService/ListGeneratePolicyTasks',
                request_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.ListGeneratePolicyTasksRequest.SerializeToString,
                response_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.ListGeneratePolicyTasksResponse.FromString,
                _registered_method=True)
        self.ArchiveGeneratePolicyTask = channel.unary_unary(
                '/clavata.gateway.v1.PoliciesService/ArchiveGeneratePolicyTask',
                request_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.ArchiveGeneratePolicyTaskRequest.SerializeToString,
                response_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.ArchiveGeneratePolicyTaskResponse.FromString,
                _registered_method=True)


class PoliciesServiceServicer(object):
    """------------ POLICIES ------------

    """

    def GetPolicy(self, request, context):
        """Get a policy by its policy ID or key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicies(self, request, context):
        """Get all policies in the account
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePolicy(self, request, context):
        """Update a policy by its policy ID or key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicyVersions(self, request, context):
        """Get all versions of a policy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActivePolicyVersions(self, request, context):
        """Get the active version of a policy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePolicy(self, request, context):
        """Delete a policy by its policy ID or key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UndeletePolicy(self, request, context):
        """Undelete a policy by its policy ID or key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetActivePolicyVersion(self, request, context):
        """Set the active version of a policy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExpungePolicyVersion(self, request, context):
        """Expunge a policy version by its version ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnexpungePolicyVersion(self, request, context):
        """Unexpunge a policy version by its version ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidatePolicy(self, request, context):
        """Validate a policy draft
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestPolicyWithDatasetItems(self, request, context):
        """Test a policy with a dataset item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestPolicy(self, request, context):
        """Test a policy with content data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePolicy(self, request, context):
        """Create a policy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePolicyVersion(self, request, context):
        """Create a policy version
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GeneratePolicyFromDataset(self, request, context):
        """Generate a policy from a dataset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGeneratePolicyTasks(self, request, context):
        """List all generate policy tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArchiveGeneratePolicyTask(self, request, context):
        """Archive a generate policy task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PoliciesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicy,
                    request_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GetPolicyRequest.FromString,
                    response_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GetPolicyResponse.SerializeToString,
            ),
            'GetPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicies,
                    request_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GetPoliciesRequest.FromString,
                    response_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GetPoliciesResponse.SerializeToString,
            ),
            'UpdatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePolicy,
                    request_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.UpdatePolicyRequest.FromString,
                    response_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.UpdatePolicyResponse.SerializeToString,
            ),
            'GetPolicyVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicyVersions,
                    request_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GetPolicyVersionsRequest.FromString,
                    response_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GetPolicyVersionsResponse.SerializeToString,
            ),
            'GetActivePolicyVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActivePolicyVersions,
                    request_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GetActivePolicyVersionsRequest.FromString,
                    response_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GetActivePolicyVersionsResponse.SerializeToString,
            ),
            'DeletePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePolicy,
                    request_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.DeletePolicyRequest.FromString,
                    response_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.DeletePolicyResponse.SerializeToString,
            ),
            'UndeletePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UndeletePolicy,
                    request_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.UndeletePolicyRequest.FromString,
                    response_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.UndeletePolicyResponse.SerializeToString,
            ),
            'SetActivePolicyVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.SetActivePolicyVersion,
                    request_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.SetActivePolicyVersionRequest.FromString,
                    response_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.SetActivePolicyVersionResponse.SerializeToString,
            ),
            'ExpungePolicyVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpungePolicyVersion,
                    request_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.ExpungePolicyVersionRequest.FromString,
                    response_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.ExpungePolicyVersionResponse.SerializeToString,
            ),
            'UnexpungePolicyVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.UnexpungePolicyVersion,
                    request_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.UnexpungePolicyVersionRequest.FromString,
                    response_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.UnexpungePolicyVersionResponse.SerializeToString,
            ),
            'ValidatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidatePolicy,
                    request_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.ValidatePolicyRequest.FromString,
                    response_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.ValidatePolicyResponse.SerializeToString,
            ),
            'TestPolicyWithDatasetItems': grpc.unary_stream_rpc_method_handler(
                    servicer.TestPolicyWithDatasetItems,
                    request_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.TestPolicyWithDatasetItemsRequest.FromString,
                    response_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.TestPolicyResponse.SerializeToString,
            ),
            'TestPolicy': grpc.unary_stream_rpc_method_handler(
                    servicer.TestPolicy,
                    request_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.TestPolicyRequest.FromString,
                    response_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.TestPolicyResponse.SerializeToString,
            ),
            'CreatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePolicy,
                    request_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.CreatePolicyRequest.FromString,
                    response_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.CreatePolicyResponse.SerializeToString,
            ),
            'CreatePolicyVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePolicyVersion,
                    request_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.CreatePolicyVersionRequest.FromString,
                    response_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.CreatePolicyVersionResponse.SerializeToString,
            ),
            'GeneratePolicyFromDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePolicyFromDataset,
                    request_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GeneratePolicyFromDatasetRequest.FromString,
                    response_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.GeneratePolicyFromDatasetResponse.SerializeToString,
            ),
            'ListGeneratePolicyTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGeneratePolicyTasks,
                    request_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.ListGeneratePolicyTasksRequest.FromString,
                    response_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.ListGeneratePolicyTasksResponse.SerializeToString,
            ),
            'ArchiveGeneratePolicyTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchiveGeneratePolicyTask,
                    request_deserializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.ArchiveGeneratePolicyTaskRequest.FromString,
                    response_serializer=clavata_dot_gateway_dot_v1_dot_policies__pb2.ArchiveGeneratePolicyTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clavata.gateway.v1.PoliciesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('clavata.gateway.v1.PoliciesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PoliciesService(object):
    """------------ POLICIES ------------

    """

    @staticmethod
    def GetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clavata.gateway.v1.PoliciesService/GetPolicy',
            clavata_dot_gateway_dot_v1_dot_policies__pb2.GetPolicyRequest.SerializeToString,
            clavata_dot_gateway_dot_v1_dot_policies__pb2.GetPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clavata.gateway.v1.PoliciesService/GetPolicies',
            clavata_dot_gateway_dot_v1_dot_policies__pb2.GetPoliciesRequest.SerializeToString,
            clavata_dot_gateway_dot_v1_dot_policies__pb2.GetPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clavata.gateway.v1.PoliciesService/UpdatePolicy',
            clavata_dot_gateway_dot_v1_dot_policies__pb2.UpdatePolicyRequest.SerializeToString,
            clavata_dot_gateway_dot_v1_dot_policies__pb2.UpdatePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicyVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clavata.gateway.v1.PoliciesService/GetPolicyVersions',
            clavata_dot_gateway_dot_v1_dot_policies__pb2.GetPolicyVersionsRequest.SerializeToString,
            clavata_dot_gateway_dot_v1_dot_policies__pb2.GetPolicyVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActivePolicyVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clavata.gateway.v1.PoliciesService/GetActivePolicyVersions',
            clavata_dot_gateway_dot_v1_dot_policies__pb2.GetActivePolicyVersionsRequest.SerializeToString,
            clavata_dot_gateway_dot_v1_dot_policies__pb2.GetActivePolicyVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clavata.gateway.v1.PoliciesService/DeletePolicy',
            clavata_dot_gateway_dot_v1_dot_policies__pb2.DeletePolicyRequest.SerializeToString,
            clavata_dot_gateway_dot_v1_dot_policies__pb2.DeletePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UndeletePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clavata.gateway.v1.PoliciesService/UndeletePolicy',
            clavata_dot_gateway_dot_v1_dot_policies__pb2.UndeletePolicyRequest.SerializeToString,
            clavata_dot_gateway_dot_v1_dot_policies__pb2.UndeletePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetActivePolicyVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clavata.gateway.v1.PoliciesService/SetActivePolicyVersion',
            clavata_dot_gateway_dot_v1_dot_policies__pb2.SetActivePolicyVersionRequest.SerializeToString,
            clavata_dot_gateway_dot_v1_dot_policies__pb2.SetActivePolicyVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExpungePolicyVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clavata.gateway.v1.PoliciesService/ExpungePolicyVersion',
            clavata_dot_gateway_dot_v1_dot_policies__pb2.ExpungePolicyVersionRequest.SerializeToString,
            clavata_dot_gateway_dot_v1_dot_policies__pb2.ExpungePolicyVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnexpungePolicyVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clavata.gateway.v1.PoliciesService/UnexpungePolicyVersion',
            clavata_dot_gateway_dot_v1_dot_policies__pb2.UnexpungePolicyVersionRequest.SerializeToString,
            clavata_dot_gateway_dot_v1_dot_policies__pb2.UnexpungePolicyVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clavata.gateway.v1.PoliciesService/ValidatePolicy',
            clavata_dot_gateway_dot_v1_dot_policies__pb2.ValidatePolicyRequest.SerializeToString,
            clavata_dot_gateway_dot_v1_dot_policies__pb2.ValidatePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestPolicyWithDatasetItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/clavata.gateway.v1.PoliciesService/TestPolicyWithDatasetItems',
            clavata_dot_gateway_dot_v1_dot_policies__pb2.TestPolicyWithDatasetItemsRequest.SerializeToString,
            clavata_dot_gateway_dot_v1_dot_policies__pb2.TestPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/clavata.gateway.v1.PoliciesService/TestPolicy',
            clavata_dot_gateway_dot_v1_dot_policies__pb2.TestPolicyRequest.SerializeToString,
            clavata_dot_gateway_dot_v1_dot_policies__pb2.TestPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clavata.gateway.v1.PoliciesService/CreatePolicy',
            clavata_dot_gateway_dot_v1_dot_policies__pb2.CreatePolicyRequest.SerializeToString,
            clavata_dot_gateway_dot_v1_dot_policies__pb2.CreatePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePolicyVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clavata.gateway.v1.PoliciesService/CreatePolicyVersion',
            clavata_dot_gateway_dot_v1_dot_policies__pb2.CreatePolicyVersionRequest.SerializeToString,
            clavata_dot_gateway_dot_v1_dot_policies__pb2.CreatePolicyVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GeneratePolicyFromDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clavata.gateway.v1.PoliciesService/GeneratePolicyFromDataset',
            clavata_dot_gateway_dot_v1_dot_policies__pb2.GeneratePolicyFromDatasetRequest.SerializeToString,
            clavata_dot_gateway_dot_v1_dot_policies__pb2.GeneratePolicyFromDatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGeneratePolicyTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clavata.gateway.v1.PoliciesService/ListGeneratePolicyTasks',
            clavata_dot_gateway_dot_v1_dot_policies__pb2.ListGeneratePolicyTasksRequest.SerializeToString,
            clavata_dot_gateway_dot_v1_dot_policies__pb2.ListGeneratePolicyTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArchiveGeneratePolicyTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clavata.gateway.v1.PoliciesService/ArchiveGeneratePolicyTask',
            clavata_dot_gateway_dot_v1_dot_policies__pb2.ArchiveGeneratePolicyTaskRequest.SerializeToString,
            clavata_dot_gateway_dot_v1_dot_policies__pb2.ArchiveGeneratePolicyTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
