from bpkio_cli.commands.archive import archive
from bpkio_cli.commands.categories import get_categories_command
from bpkio_cli.commands.configure import configure
from bpkio_cli.commands.consumption import consumption
from bpkio_cli.commands.doctor import doctor
from bpkio_cli.commands.hello import hello
from bpkio_cli.commands.memory import memory
from bpkio_cli.commands.package import package
from bpkio_cli.commands.plugins import plugins
from bpkio_cli.commands.profiles import profile
from bpkio_cli.commands.recorder import record
from bpkio_cli.commands.services import get_services_commands
from bpkio_cli.commands.sessions import session
from bpkio_cli.commands.sources import get_sources_commands
from bpkio_cli.commands.update import update
from bpkio_cli.commands.url import url
from bpkio_cli.commands.users import get_users_commands
