import tensorflow_probability as tfp
from zfit_interface.data import ZfitData

class UnbinnedData(tfp.experimental.AutoCompositeTensor, ZfitData):
    def __init__(self, data, space=None, weights=None) -> None: ...
    @property
    def is_binned(self): ...
    @property
    def is_unbinned(self): ...
    @property
    def space(self): ...
    @property
    def data(self): ...
    @property
    def weights(self): ...
    def values(self): ...
    def __getitem__(self, item): ...
    @property
    def has_weights(self): ...
