# -------------------------------------------------------------------
# This file was auto-generated. Do not edit directly.
# Generated by: StageGeneratorV2
# -------------------------------------------------------------------

from typing import TYPE_CHECKING

from ibm_watsonx_data_integration.services.datastage.models.flow.dag import StageNode
from ibm_watsonx_data_integration.services.datastage.models.stage_models.mysql_amazon import mysql_amazon

from ibm_watsonx_data_integration.cpd_models.connections_model import Connection
from ibm_watsonx_data_integration.services.datastage.models.connections.mysql_amazon_connection import MysqlAmazonConn


if TYPE_CHECKING:
    from ibm_watsonx_data_integration.services.datastage.models.flow.dag import DAG



class AmazonRDSForMysqlStage(StageNode):
    def __init__(self, dag: "DAG", configuration: mysql_amazon=None, *, label: str = None):
        super().__init__(dag, configuration=configuration, label=label)
        self.configuration: mysql_amazon = configuration or mysql_amazon()

    def use_connection(self, connection: Connection):
        self.configuration.connection = MysqlAmazonConn().from_connection(connection)
