from __future__ import annotations

from pararamio._core.exceptions import (
    PararamioAuthenticationError,
    PararamioCaptchaAuthenticationError,
    PararamioException,
    PararamioHTTPRequestError,
    PararamioLimitExceededError,
    PararamioMethodNotAllowedError,
    PararamioPasswordAuthenticationError,
    PararamioRequestError,
    PararamioSecondFactorAuthenticationError,
    PararamioServerResponseError,
    PararamioTypeError,
    PararamioValidationError,
    PararamioXSRFRequestError,
    PararamModelNotLoadedError,
    PararamMultipleFoundError,
    PararamNoNextPostError,
    PararamNoPrevPostError,
    PararamNotFoundError,
)

__all__ = (
    'PararamModelNotLoadedError',
    'PararamMultipleFoundError',
    'PararamNoNextPostError',
    'PararamNoPrevPostError',
    'PararamNotFoundError',
    'PararamioAuthenticationError',
    'PararamioCaptchaAuthenticationError',
    'PararamioException',
    'PararamioHTTPRequestError',
    'PararamioLimitExceededError',
    'PararamioMethodNotAllowedError',
    'PararamioPasswordAuthenticationError',
    'PararamioRequestError',
    'PararamioSecondFactorAuthenticationError',
    'PararamioServerResponseError',
    'PararamioTypeError',
    'PararamioValidationError',
    'PararamioXSRFRequestError',
)
