_DEFAULT_PANDAS_DATASOURCE_NAME = "kedro_df_in_memory"

_DEFAULT_BATCH_DEFINITION_WHOLE_DATAFRAME_NAME = "kedro_whole_df"

CONSTANT_EMAIL_SETTING_STORE = "STORE"
CONSTANT_EMAIL_SETTING_CUMULATE = "CUMULATE"
