# coding: utf-8

"""
    Sonatype Lifecycle Public REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.196.0-01
    Contact: community@sonatype.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sonatype_iq_api_client.api.policy_waivers_api import PolicyWaiversApi


class TestPolicyWaiversApi(unittest.TestCase):
    """PolicyWaiversApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PolicyWaiversApi()

    def tearDown(self) -> None:
        pass

    def test_add_bulk_policy_waivers(self) -> None:
        """Test case for add_bulk_policy_waivers

        """
        pass

    def test_add_policy_waiver_by_policy_violation_id(self) -> None:
        """Test case for add_policy_waiver_by_policy_violation_id

        """
        pass

    def test_add_waiver_to_transitive_policy_violations_by_app_scan_component(self) -> None:
        """Test case for add_waiver_to_transitive_policy_violations_by_app_scan_component

        """
        pass

    def test_add_waiver_to_transitive_policy_violations_by_owner_stage_component(self) -> None:
        """Test case for add_waiver_to_transitive_policy_violations_by_owner_stage_component

        """
        pass

    def test_delete_policy_waiver(self) -> None:
        """Test case for delete_policy_waiver

        """
        pass

    def test_get_policy_waiver(self) -> None:
        """Test case for get_policy_waiver

        """
        pass

    def test_get_policy_waivers(self) -> None:
        """Test case for get_policy_waivers

        """
        pass

    def test_get_transitive_policy_waivers_by_app_scan_component(self) -> None:
        """Test case for get_transitive_policy_waivers_by_app_scan_component

        """
        pass

    def test_request_policy_waiver(self) -> None:
        """Test case for request_policy_waiver

        """
        pass

    def test_update_policy_waiver(self) -> None:
        """Test case for update_policy_waiver

        """
        pass


if __name__ == '__main__':
    unittest.main()
