# (generated with --quick)

import argparse
import lithi
import logging
import pathlib
import sys
from lithi import commands

Cli: type[lithi.core.cli.Cli]
ConfigManager: type[lithi.core.config.ConfigManager]
Logger: type[lithi.core.logger.Logger]
Settings: type[lithi.bizlog.settings.Settings]
TargetFactory: type[lithi.interface.target.TargetFactory]
__version__: str
logger: lithi.core.logger._GlobalLoggerProxy

def app() -> None: ...
def get_cache_dirpath() -> pathlib.Path: ...
def get_config_dirpath() -> pathlib.Path: ...
def get_config_name() -> str: ...
def get_logo() -> str: ...
def get_name() -> str: ...
def on_cli_init(_: lithi.core.cli.Cli, args: argparse.Namespace) -> None: ...
def on_cli_no_command(cli: lithi.core.cli.Cli, args: argparse.Namespace) -> None: ...
def set_app_name(name: str) -> None: ...
