from _typeshed import Incomplete
from rich.console import Console

class FileLoggingConsole(Console):
    log_file_path: Incomplete
    log_file: Incomplete
    def __init__(self, log_file_path, *args, **kwargs) -> None: ...
    def print(self, *args, **kwargs) -> None: ...
    def __del__(self) -> None: ...

class Logger:
    def __new__(cls, log_dir: str = './logs', *args, **kwargs): ...
    def get_logger(self): ...
    def get_console(self): ...
