"""Centralized HTML ID constants for the application"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/html_ids.ipynb.

# %% auto 0
__all__ = ['HtmlIds']

# %% ../../nbs/core/html_ids.ipynb 3
class HtmlIds:
    """HTML ID constants used throughout the application."""

    # Process management
    PROCESS_COUNT = "process-count"
    PROCESS_STATUS = "process-status"

    # Tables
    CPU_PROCESSES_TABLE = "cpu-processes-table"
    MEMORY_PROCESSES_TABLE = "memory-processes-table"
    GPU_PROCESSES_TABLE = "gpu-processes-table"  # NEW - for GPU processes table
    GPU_PROCESSES_TABLE_BODY = "gpu-processes-table-body"  # NEW - for GPU processes table body

    # Card bodies (main content containers)
    CPU_CARD_BODY = "cpu-card-body"
    MEMORY_CARD_BODY = "memory-card-body"
    DISK_CARD_BODY = "disk-card-body"
    NETWORK_CARD_BODY = "network-card-body"
    PROCESS_CARD_BODY = "process-card-body"
    GPU_CARD_BODY = "gpu-card-body"
    TEMPERATURE_CARD_BODY = "temperature-card-body"

    # Card containers
    CPU_CARD = "cpu-card"
    MEMORY_CARD = "memory-card"
    DISK_CARD = "disk-card"
    NETWORK_CARD = "network-card"
    PROCESS_CARD = "process-card"
    GPU_CARD = "gpu-card"
    TEMPERATURE_CARD = "temperature-card"

    # Tab navigation
    CPU_TAB = "cpu-tab"
    MEM_TAB = "mem-tab"

    # Tab content containers
    CPU_PROCESSES = "cpu-processes"
    MEMORY_PROCESSES = "memory-processes"

    # Settings modal
    SETTINGS_MODAL = "settings_modal"

    # Interval controls
    CPU_INTERVAL = "cpu-interval"
    CPU_INTERVAL_VALUE = "cpu-interval-value"
    MEMORY_INTERVAL = "memory-interval"
    MEMORY_INTERVAL_VALUE = "memory-interval-value"
    DISK_INTERVAL = "disk-interval"
    DISK_INTERVAL_VALUE = "disk-interval-value"
    NETWORK_INTERVAL = "network-interval"
    NETWORK_INTERVAL_VALUE = "network-interval-value"
    PROCESS_INTERVAL = "process-interval"
    PROCESS_INTERVAL_VALUE = "process-interval-value"
    GPU_INTERVAL = "gpu-interval"
    GPU_INTERVAL_VALUE = "gpu-interval-value"
    TEMPERATURE_INTERVAL = "temperature-interval"
    TEMPERATURE_INTERVAL_VALUE = "temperature-interval-value"

    # SSE and status
    SSE_CONNECTION = "sse-connection"
    CONNECTION_STATUS = "connection-status"
    TIMESTAMP = "timestamp"

    # NEW - Granular content sections for better scroll preservation
    # GPU card sections
    GPU_METRICS = "gpu-metrics"  # GPU utilization, memory, temp, power metrics
    GPU_PROCESSES_SECTION = "gpu-processes-section"  # Entire GPU processes section

    # Network card sections
    NETWORK_INTERFACES = "network-interfaces"  # Network interfaces list
    NETWORK_CONNECTIONS = "network-connections"  # Connection statistics

    # Disk card sections
    DISK_ENTRIES = "disk-entries"  # Disk entries list

    # Temperature card sections
    TEMPERATURE_SENSORS = "temperature-sensors"  # Temperature sensors list

    @staticmethod
    def as_selector(id_str: str) -> str:
        """Convert an ID to a CSS selector format (with #)."""
        return f"#{id_str}"
