# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel, UnionMetadata
from .advanced_mode_transform_config_chunking_config import AdvancedModeTransformConfigChunkingConfig
from .advanced_mode_transform_config_segmentation_config import AdvancedModeTransformConfigSegmentationConfig


class PipelineTransformConfig_Auto(UncheckedBaseModel):
    """
    Configuration for the transformation.
    """

    mode: typing.Literal["auto"] = "auto"
    chunk_size: typing.Optional[int] = None
    chunk_overlap: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class PipelineTransformConfig_Advanced(UncheckedBaseModel):
    """
    Configuration for the transformation.
    """

    mode: typing.Literal["advanced"] = "advanced"
    segmentation_config: typing.Optional[AdvancedModeTransformConfigSegmentationConfig] = None
    chunking_config: typing.Optional[AdvancedModeTransformConfigChunkingConfig] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


PipelineTransformConfig = typing_extensions.Annotated[
    typing.Union[PipelineTransformConfig_Auto, PipelineTransformConfig_Advanced], UnionMetadata(discriminant="mode")
]
