class KuiperError(BaseException):
    start: int | None
    end: int | None
    ...

class KuiperCompileError(KuiperError): ...
class KuiperRuntimeError(KuiperError): ...

class KuiperExpression:
    def run(self, input: str) -> str: ...
    def run_multiple_inputs(self, inputs: list[str]) -> str: ...

def compile_expression(
    expression: str, inputs: list[str], optimizer_operation_limit=100000, max_macro_expansions=20
) -> KuiperExpression: ...
