from enum import Enum


class DatabaseTable(Enum):
    Tag = "tag"
    Topic = "topic"
    Subject = "subject"
    Settings = "setting"
    AutoSetting = "auto_setting"
    Bookmark = "bookmark"
    MdxNote = "mdx_note"
    FrontMatter = "front_matter"
    FrontMatterTag = "front_matter_tag"
    MdxNoteTag = "mdx_note_tag"
    MdxNoteEquation = "mdx_note_equation"
    MdxNoteSnippet = "mdx_note_snippet"
    MdxNoteTopic = "mdx_note_topic"
    MdxNoteSubject = "mdx_note_subject"
    MdxNoteDictionaryEntry = "mdx_note_dictionary_entry"
    MdxNoteLink = "mdx_note_link"
    DictionaryEntry = "dictionary_entry"
    BibEntry = "bib_entry"
    MdxNoteBibEntry = "mdx_note_bib_entry"
    Snippet = "snippet"
    SnippetTag = "snippet_tag"
    Equation = "equation"
    EquationSnippets = "equation_snippet"
    EquationTag = "equation_tag"
    TaskList = "task_list"
    Task = "task"
    TaskTag = "task_tag"
    AiChat = "ai_chat"
    AiChatMessage = "ai_chat_message"
    KanbanBoard = "kanban_board"
    KanbanBoardTaskList = "kanban_board_task_list"
    KanbanBoardEntry = "kanban_board_entry"
    KanbanBoardList = "kanban_board_list"
    Whiteboard = "whiteboard"
    Vector = "vector"
