from enum import StrEnum


class EmojiSceneType(StrEnum):
    NONE = "NONE"
    ACTMULTIV3_ROOM = "ACTMULTIV3_ROOM"
    ACTMULTIV3_PICK = "ACTMULTIV3_PICK"
    ACTMULTIV3_BATTLE = "ACTMULTIV3_BATTLE"
    ENEMYDUEL_BATTLE = "ENEMYDUEL_BATTLE"
