from ..settings import ztypes as ztypes

def generate_1d_grid(data, num_grid_points, absolute_boundary: float = 0.0, relative_boundary: float = 0.05): ...
def bin_1d(binning_method, data, grid, weights=None): ...
def bin_1d_simple(data, grid, weights=None): ...
def bin_1d_linear(data, grid, weights=None): ...
