from . import root_search as root_search
from ..settings import ztypes as ztypes

def find_practical_support_bandwidth(kernel, bandwidth, absolute_tolerance: float = 0.0001): ...
def convolve_1d_data_with_kernel(kernel, bandwidth, data, grid, support=None, fft_method: str = 'conv1d'): ...
