"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .accountresponse import AccountResponse, AccountResponseTypedDict
from .errorresponse import ErrorResponse, ErrorResponseTypedDict
from typing import Union
from typing_extensions import TypeAliasType


GetAccountDetailsResponseTypedDict = TypeAliasType(
    "GetAccountDetailsResponseTypedDict",
    Union[ErrorResponseTypedDict, AccountResponseTypedDict],
)


GetAccountDetailsResponse = TypeAliasType(
    "GetAccountDetailsResponse", Union[ErrorResponse, AccountResponse]
)
