"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errorresponse import ErrorResponse, ErrorResponseTypedDict
from .groupresponse import GroupResponse, GroupResponseTypedDict
from typing import List, Union
from typing_extensions import TypeAliasType


ListGroupsResponseTypedDict = TypeAliasType(
    "ListGroupsResponseTypedDict",
    Union[ErrorResponseTypedDict, List[GroupResponseTypedDict]],
)


ListGroupsResponse = TypeAliasType(
    "ListGroupsResponse", Union[ErrorResponse, List[GroupResponse]]
)
