# Generated by Django 3.2.11 on 2022-04-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0019_descargacfdi_metodo_descarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descargacfdi',
            name='metodo_descarga',
            field=models.IntegerField(choices=[(1, 'Web service'), (2, 'SAT Scraper')], null=True),
        ),
    ]
